/* B7 FI Command Center v0.47.0 — Meeting Notes + Legacy Reference + Framework QA */
(function(){
const VERSION='0.47.0';
function today47(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function ensure47(){
 state.meetings=state.meetings||{}; state.meetingHistory=Array.isArray(state.meetingHistory)?state.meetingHistory:[];
 state.referenceFiles=state.referenceFiles||{};
 if(!state.referenceFiles.legacyNotes)state.referenceFiles.legacyNotes={name:'',loadedAt:''};
 if(typeof referenceSession!=='undefined'&&!('legacyNotes' in referenceSession))referenceSession.legacyNotes=null;
}
ensure47();
function morningRec47(){
 const d=today47(),r=state.meetings[d]||(state.meetings[d]={date:d,notes:'',created:new Date().toISOString()});
 r.toolNotes=r.toolNotes&&typeof r.toolNotes==='object'?r.toolNotes:{}; r.generalNotes=r.generalNotes||'';
 if(r.notes&&!r.generalNotes&&!Object.keys(r.toolNotes).length)r.generalNotes=r.notes;
 return r;
}
function snapshotText47(r,arr){let out=[];arr.forEach(t=>{let n=(r.toolNotes[t.id]||'').trim();if(n)out.push(`${t.id}\n${n}`)});if((r.generalNotes||'').trim())out.push(`GENERAL NOTES\n${r.generalNotes.trim()}`);return out.join('\n\n')}
function archive47(){let r=morningRec47(),a=typeof orderedMorningTools==='function'?orderedMorningTools():pageTools('morning');r.notes=snapshotText47(r,a);state.meetingHistory=state.meetingHistory.filter(x=>x.date!==r.date);state.meetingHistory.unshift({...clone(r),closed:new Date().toISOString()});save();morning()}
function hist47(x){
 let tn=x.toolNotes&&typeof x.toolNotes==='object'?x.toolNotes:{};let count=Object.values(tn).filter(v=>String(v||'').trim()).length+(String(x.generalNotes||'').trim()?1:0);
 let body=Object.entries(tn).filter(([,v])=>String(v||'').trim()).map(([id,v])=>`<div class="meeting-history-tool"><b>${esc(id)}</b><div>${esc(v).replace(/\n/g,'<br>')}</div></div>`).join('');
 if(x.generalNotes)body+=`<div class="meeting-history-tool general"><b>GENERAL NOTES</b><div>${esc(x.generalNotes).replace(/\n/g,'<br>')}</div></div>`;
 if(!body)body=typeof statusHtml==='function'?statusHtml(x.notes,'No notes recorded.'):`<div>${esc(x.notes||'No notes recorded.')}</div>`;
 return `<details><summary>${fmt(x.date)} · ${count} note section${count===1?'':'s'}</summary><div class="meeting-history-body">${body}</div></details>`
}
/* Preformatted morning notebook: every active tool is always ready for typing. */
morning=function(){
 let a=typeof orderedMorningTools==='function'?orderedMorningTools():pageTools('morning'),rec=morningRec47();
 app.innerHTML=`<div class="report-screen">${reportHeader('B7 FI MORNING STATUS')}<div class="meeting-control-strip"><div><b>${fmt(rec.date)}</b><span>${a.length} systems</span><span>${state.workspaceTasks.filter(x=>x.status!=='Completed').length} open actions</span></div><button id="resetMorningOrder" class="btn small">Reset Tool Type / Serial Order</button></div>${a.map((t,i)=>{let visible=morningNcs(t),normal=visible.filter(n=>!isEscalatedNc(n)),escal=visible.filter(isEscalatedNc),active=activeChecklists(t),checklistText=packingActive(t)?'200 — Packing':active.length?active.map(x=>`${x[0]}: ${x[1]}`).join(' + '):`${t.checklist}: ${checkName(t)}`;return `<div class="meeting-row v21-meeting-row"><div class="meeting-order-controls"><span>${i+1}</span><button data-move="${esc(t.id)}" data-d="-1" ${i===0?'disabled':''}>↑</button><button data-move="${esc(t.id)}" data-d="1" ${i===a.length-1?'disabled':''}>↓</button></div><div class="meeting-content"><div class="meeting-main">${esc(t.id)} (${esc(t.room)}${t.bay?' / '+esc(t.bay):''}) (${esc(t.model)} - ${esc(t.codename)}) (SW: ${esc(t.sw||'—')}) ${esc(checklistText)} (${esc(t.customer)}, ${fmt(t.ship)}) <span class="morning-lamp">(Lamp Hours: ${t.lamp||0})</span> ${typeof latestChangeBadge==='function'?latestChangeBadge(t):''} ${packingActive(t)?`<span class="phase-chip packing">PACKING ${packingProgress(t)}%</span>`:''} ${t.sourceRequired==='Yes'?`<span class="phase-chip source">SOURCE: ${esc(t.sourceStatus)}</span>`:''} ${t.strRequired==='Yes'?`<span class="phase-chip str">STR: ${esc(t.strStatus)}</span>`:''}</div>${statusHtml(t.activity)}<ul class="meeting-bullets">${normal.map(n=>`<li class="morning-open-nc">${esc(n.id)}: ${esc(n.desc)}</li>`).join('')}${escal.map(n=>`<li class="morning-escalated">Escalated ${esc(n.id)}${n.days?` - ${n.days} Days`:''}: ${esc(n.desc)}</li>`).join('')}</ul></div></div>`}).join('')}
 <section class="panel morning-notes-panel preformatted-notebook"><div class="subsection-title"><div><h3>Morning Meeting Notebook · ${fmt(rec.date)}</h3><p class="gray">Every active tool is preloaded. Type only where a note is needed; blank sections stay blank in the saved snapshot.</p></div><button id="archiveMeeting" class="btn">End / Save Meeting Snapshot</button></div><div class="meeting-note-grid">${a.map(t=>`<div class="tool-note-entry"><div class="tool-note-label"><b>${esc(t.id)}</b><span>${esc(t.codename)} · ${esc(t.model)} · ${esc(t.customer)}</span></div><textarea data-meeting-tool="${esc(t.id)}" rows="3" placeholder="Notes for ${esc(t.id)}…">${esc(rec.toolNotes[t.id]||'')}</textarea></div>`).join('')}</div><div class="general-note-entry"><div class="tool-note-label"><b>GENERAL NOTES</b><span>Items not tied to a specific tool</span></div><textarea id="meetingGeneralNotes" rows="4" placeholder="General meeting notes…">${esc(rec.generalNotes||'')}</textarea></div><div class="meeting-action-builder"><input id="meetingTaskTitle" placeholder="Action item from this meeting"><select id="meetingTaskTool"><option value="">General / No Tool</option>${a.map(t=>`<option value="${esc(t.id)}">${esc(t.id)} · ${esc(t.codename)}</option>`).join('')}</select><button id="meetingAddTask" class="btn primary">Add to Tasks</button></div><div class="meeting-history"><h4>Meeting History</h4>${state.meetingHistory.slice(0,20).map(hist47).join('')||'<span class="gray">No archived morning meetings yet.</span>'}</div></section></div>`;
 document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>moveMorning(b.dataset.move,Number(b.dataset.d)));let reset=$('#resetMorningOrder');if(reset)reset.onclick=()=>{state.morningOrder=[];save();morning()};
 document.querySelectorAll('[data-meeting-tool]').forEach(x=>x.oninput=e=>{rec.toolNotes[e.target.dataset.meetingTool]=e.target.value;save()});let gn=$('#meetingGeneralNotes');if(gn)gn.oninput=e=>{rec.generalNotes=e.target.value;save()};
 let add=$('#meetingAddTask');if(add)add.onclick=()=>{addMorningTask($('#meetingTaskTitle').value,$('#meetingTaskTool').value);$('#meetingTaskTitle').value='';updateOperationsBar()};let ar=$('#archiveMeeting');if(ar)ar.onclick=archive47;
 actions([{label:'Morning Quick Update',primary:true,fn:()=>admin('meeting')},{label:'FI Knowledge Base',fn:()=>workspace('reference')},{label:'Lead Workspace / Actions',fn:()=>setView('workspace')},{label:'Administration',fn:()=>setView('admin')}]);
};

function legacyCard47(){let meta=state.referenceFiles.legacyNotes||{},sess=referenceSession.legacyNotes;return `<section class="reference-file-card legacy-reference-card"><div class="reference-file-head"><div><h3>Legacy FI Notes / Word Reference</h3><p>Your original working notes document. Keep it beside the new FI Knowledge Base during the transition.</p></div><span class="reference-mode">LEGACY REFERENCE · READ ONLY</span></div><div class="reference-file-meta"><b>${esc(sess?.file?.name||meta.name||'No legacy document loaded')}</b><span>${meta.loadedAt?`Last selected ${new Date(meta.loadedAt).toLocaleString()}`:'Select the current Word/PDF/TXT reference document'}</span></div><div class="reference-file-actions"><label class="btn primary file-btn">${meta.name?'Replace':'Load'} Legacy Notes<input id="legacyNotesInput47" type="file" accept=".doc,.docx,.pdf,.txt,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/pdf,text/plain" hidden></label><button id="legacyOpen47" class="btn" ${sess?'':'disabled'}>Open Original</button></div><div id="legacyPreview47" class="reference-preview"><div class="reference-preview-empty">${sess?'Document loaded.':'Select the legacy document to keep it available from Reference Files.'}</div></div></section>`}
function legacyPreview47(){let s=referenceSession.legacyNotes,b=$('#legacyPreview47');if(!s||!b)return;let n=(s.file.name||'').toLowerCase();if(n.endsWith('.pdf')||n.endsWith('.txt'))b.innerHTML=`<iframe class="legacy-doc-frame" src="${s.url}" title="Legacy FI Notes preview"></iframe>`;else b.innerHTML=`<div class="legacy-word-ready"><b>Word document ready for reference</b><p>${esc(s.file.name)}</p><p>Use <b>Open Original</b> to view the actual Word document in the browser/Word application. The Command Center keeps this reference read-only.</p></div>`}
const oldRefs47=referencesPage;
referencesPage=function(){oldRefs47();let dash=document.querySelector('.reference-dashboard');if(dash&&!document.querySelector('.legacy-reference-card'))dash.insertAdjacentHTML('beforeend',legacyCard47());let inp=$('#legacyNotesInput47');if(inp)inp.onchange=()=>{let f=inp.files?.[0];if(!f)return;if(referenceSession.legacyNotes?.url)URL.revokeObjectURL(referenceSession.legacyNotes.url);referenceSession.legacyNotes={file:f,url:URL.createObjectURL(f)};state.referenceFiles.legacyNotes={name:f.name,loadedAt:new Date().toISOString()};save();referencesPage();setTimeout(legacyPreview47,0)};let op=$('#legacyOpen47');if(op)op.onclick=()=>{let s=referenceSession.legacyNotes;if(!s)return alert('Reload/select the legacy document in this browser session first.');window.open(s.url,'_blank')};if(referenceSession.legacyNotes)setTimeout(legacyPreview47,0);actions([{label:'FI Knowledge Base',primary:true,fn:()=>workspace('reference')},{label:'Tool Countdown',fn:()=>setView('countdown')},{label:'Shipping Schedule',fn:()=>setView('shipping')}],false)};

/* Rename the existing permanent Reference workspace into the operational knowledge base. */
const oldWorkspace47=workspace;
workspace=function(tab='tasks'){oldWorkspace47(tab);if(tab==='reference'){let h=[...document.querySelectorAll('#app h3')].find(x=>x.textContent.trim()==='Reference');if(h)h.textContent='FI Knowledge Base / Special Notes';let p=h?.nextElementSibling;if(p&&p.classList.contains('helper'))p.textContent='Searchable permanent reference for part numbers, procedures, recurring reminders, wafer information, contacts, error codes and special FI notes.';actions([{label:'Action Center',fn:()=>workspace('tasks')},{label:'Reference Files',fn:()=>setView('references')},{label:'Administration',fn:()=>setView('admin')}],false)}};

/* Keep v0.46 ticker alive even after pages replaced by patch functions. */
const render47=render;render=function(){render47();setTimeout(()=>{try{if(typeof refreshTopActions46==='function')refreshTopActions46(false);else if(typeof renderTopActionBar==='function')renderTopActionBar();updateOperationsBar()}catch(e){}},0)};
document.title=`B7 FI Command Center v${VERSION}`;let v=document.getElementById('appVersionLabel');if(v)v.textContent=`B7 FI Command Center v${VERSION}`;setTimeout(()=>{try{render()}catch(e){console.error('v0.47.0',e)}},0);
})();
