/* B7 FI Command Center v0.80.38 — single master Tool page + canonical tool routing.
   - One purple Tool page is the canonical editable record for a Tool.
   - Tool Detail and Tool Edit are collapsed into one vertically scrolling page.
   - No secondary tab navigation; the global Page Navigation bar is the only toolbar.
   - Custom-field definition/management remains in Administration Center.
   - Operations/Tool Center/Shipping/Status links all resolve to this master Tool page.
   - Live Status Only remains read-only and is intentionally not changed by this patch.
*/
(function(){
'use strict';
const VERSION='0.80.38';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const idSafe=s=>String(s||'').replace(/[^A-Za-z0-9_-]/g,'_');
window.B7_APP_VERSION=VERSION; window.VERSION=VERSION;
function stamp(){document.title=`B7 FI Command Center v${VERSION}`;const v=$('#appVersionLabel');if(v)v.textContent=`B7 FI COMMAND CENTER V${VERSION}`}
function qFromDate(v){const m=String(v||'').match(/^(\d{4})-(\d{2})/);return m?`CY${m[1].slice(-2)}Q${Math.floor((+m[2]-1)/3)+1}`:''}
function currentQuarter(){try{return typeof quarterLabel==='function'?quarterLabel():'CY26Q3'}catch(e){return'CY26Q3'}}
function getTools(){try{return tools||[]}catch(e){return[]}}
function toolById(id){return getTools().find(t=>String(t.id)===String(id))}
function remember(route){try{sessionStorage.setItem('b7.route',JSON.stringify(route));history.replaceState(route,'',location.pathname+'#'+encodeURIComponent(JSON.stringify(route)))}catch(e){}}
function purple(title){document.body.dataset.center='toolfinal';document.body.dataset.theme='toolcenter';document.documentElement.style.setProperty('--page-accent','#8b5cf6');document.documentElement.style.setProperty('--page-accent-rgb','139,92,246');document.documentElement.style.setProperty('--center-color','#8b5cf6');document.documentElement.style.setProperty('--center-rgb','139,92,246');$$('.main-nav .nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view==='toolcenter'));const h=$('#headerPageTitle');if(h)h.textContent=title}
function btn(label,fn,primary=false,danger=false){const b=document.createElement('button');b.type='button';b.className=`btn${primary?' primary':''}${danger?' danger':''}`;b.textContent=label;b.onclick=fn;return b}
function toolbar(left,right){const bar=$('#floatingActions');if(!bar)return;bar.className='floating-actions page-toolbar v838-page-toolbar';bar.innerHTML='';const l=document.createElement('div'),r=document.createElement('div');l.className='v838-toolbar-left';r.className='v838-toolbar-right';left.filter(Boolean).forEach(x=>l.appendChild(x));right.filter(Boolean).forEach(x=>r.appendChild(x));bar.append(l,r)}
function shot(){try{if(typeof enterScreenshotMode==='function')return enterScreenshotMode()}catch(e){}window.print()}
function report(){window.print()}
function select(options,value){return options.map(x=>`<option value="${esc(x)}" ${String(x)===String(value)?'selected':''}>${esc(x)}</option>`).join('')}
function input(label,id,value,type='text',extra=''){return `<div class="form-group"><label>${esc(label)}</label><input id="${id}" type="${type}" value="${esc(value??'')}" ${extra}></div>`}
function textarea(label,id,value,wide=true){return `<div class="form-group${wide?' wide':''}"><label>${esc(label)}</label><textarea id="${id}">${esc(value??'')}</textarea></div>`}
function routeHtml(t){try{return routeWorkflow(t,true)}catch(e){return'<p class="gray">Checklist route unavailable.</p>'}}
function leadHtml(t){try{return leadWorkflow(t,true)}catch(e){return'<p class="gray">Lead / Admin workflow unavailable.</p>'}}
function routePct(t){try{return routeProgress(t)}catch(e){return 0}}
function leadPct(t){try{return adminProgress(t)}catch(e){return 0}}
function routeOpts(t){try{return routeOptions(t)}catch(e){return''}}
function leadMasterOpts(t){try{let a=activeLeadTasks().filter(x=>x.countProgress!==false);return `<option value="">Not Set</option>`+a.map(x=>`<option value="${esc(x.id)}" ${x.id===t.currentLeadAdminTask?'selected':''}>${esc(x.label)}</option>`).join('')}catch(e){return '<option value="">Not Set</option>'}}
function codeOpts(t){try{return codenameOptions(t.codename)}catch(e){return`<option>${esc(t.codename||'Panamera')}</option>`}}
function modelOpts(t){try{return modelOptions(t.codename,t.model)}catch(e){return`<option>${esc(t.model||'')}</option>`}}
function quarterOpts(v){try{return quarterOptions(v)}catch(e){return select(['CY26Q1','CY26Q2','CY26Q3','CY26Q4','CY27Q1','CY27Q2','CY27Q3','CY27Q4'],v)}}
function mstIsApplicable(t){try{return mstApplicable(t)}catch(e){return['Regera','Celestiq'].includes(t.codename)}}
function normalizeTool(t){try{return normalize(t)}catch(e){return t}}
function newTool(){try{return normalizeTool(defaultTool())}catch(e){return {id:'',family:'29XX',codename:'Panamera',model:'2935',quarter:currentQuarter(),customer:'N/A',so:'N/A',ship:'',quarterStatus:'Waiting for FI',room:'CR1',bay:'',driver:'Unassigned',sw:'',process:'Full Process',lamp:0,notes:'',activity:'',checklist:'FI_130_010',checklistStates:{},escalationMeeting:'N/A',poa:'N/A',fiStatus:'Progressing',waivers:'',ncs:[],leadAdmin:{},schedule:{publish:'N/A',status:'N/A',subsystems:'',cables:'',accessories:'',mst:'N/A',is:'',notes:''},sourceRequired:'TBD',sourceStatus:'Not Started',sourceHandoff:'',sourceStart:'',sourceComplete:'',strRequired:'TBD',strStatus:'Not Started',strDue:'',strNotes:'',changeHistory:[]}}}
function ncRows(t){return (t.ncs||[]).map((n,i)=>`<div class="nc-card v838-nc-row" data-nc-index="${i}"><div class="form-grid">${input('NC #',`v838-nc-id-${i}`,n.id)}${input('Description',`v838-nc-desc-${i}`,n.desc)}<div class="form-group"><label>Status</label><select id="v838-nc-state-${i}">${select(['Open','Troubleshooting','Escalated','POA In Progress','Waiver Pending','Closed','Waived'],n.state||'Open')}</select></div>${input('Escalation Days',`v838-nc-days-${i}`,n.days||0,'number')}</div><label class="v838-check"><input id="v838-nc-block-${i}" type="checkbox" ${n.blocking?'checked':''}> Blocking FI progression</label><button type="button" class="btn danger small v838-remove-nc" data-i="${i}">Remove</button></div>`).join('')||'<p class="gray">No critical NCs tracked.</p>'}
function historyHtml(t){const a=(t.changeHistory||[]).slice(0,12);return a.length?`<div class="v838-history">${a.map(h=>`<div><b>${esc(h.type||h.field||'CHANGE')}</b><span>${esc(h.oldValue||'—')} → ${esc(h.newValue||'—')}</span><small>${esc(h.reason||'')}${h.changedAt?` · ${esc(new Date(h.changedAt).toLocaleString())}`:''}</small></div>`).join('')}</div>`:'<p class="gray">No plan changes recorded.</p>'}
function collect(t,original){
  const val=id=>$(id)?.value??'';
  const oldShip=original?.ship||'', oldQ=original?.quarter||qFromDate(oldShip)||'';
  t.family='29XX';t.codename=val('#tm-code');t.model=val('#tm-model');t.id=val('#tm-id').trim();t.so=val('#tm-so');t.customer=val('#tm-customer');t.room=val('#tm-room');t.bay=val('#tm-bay');t.quarterStatus=val('#tm-status');t.driver=val('#tm-driver');t.ship=val('#tm-ship');t.sw=val('#tm-sw');t.process=val('#tm-process');t.lamp=Number(val('#tm-lamp'))||0;t.notes=val('#tm-notes');t.activity=val('#tm-activity');t.quarter=val('#tm-quarter')||qFromDate(t.ship)||currentQuarter();
  t.checklist=val('#tm-check')||t.checklist;t.microTargetChecklist=val('#tm-micro');t.currentLeadAdminTask=val('#tm-lead-current');t.escalationMeeting=val('#tm-escalation')||'N/A';t.poa=val('#tm-poa')||'N/A';t.fiStatus=val('#tm-fistatus')||'Progressing';t.waivers=val('#tm-waivers');t.checklistStates=t.checklistStates||{};$$('[data-check-code]').forEach(x=>t.checklistStates[x.dataset.checkCode]=x.value);
  t.leadAdmin=t.leadAdmin||{};$$('[data-task-id]').forEach(x=>t.leadAdmin[x.dataset.taskId]=x.value);
  t.sourceRequired=val('#tm-source-required')||'TBD';t.sourceStatus=val('#tm-source-status')||'Not Started';t.sourceHandoff=val('#tm-source-handoff');t.sourceStart=val('#tm-source-start');t.sourceComplete=val('#tm-source-complete');t.strRequired=val('#tm-str-required')||'TBD';t.strStatus=val('#tm-str-status')||'Not Started';t.strDue=val('#tm-str-due');t.strNotes=val('#tm-str-notes');
  t.schedule=t.schedule||{};t.schedule.publish=val('#tm-sch-pub')||'N/A';t.schedule.status=val('#tm-sch-status')||'N/A';t.schedule.subsystems=val('#tm-sch-sub');t.schedule.cables=val('#tm-sch-cables');t.schedule.accessories=val('#tm-sch-acc');t.schedule.mst=mstIsApplicable(t)?val('#tm-sch-mst'):'N/A';t.schedule.is=val('#tm-sch-is');t.schedule.notes=val('#tm-sch-notes');
  t.ncs=$$('.v838-nc-row').map((r,i)=>({id:val(`#v838-nc-id-${i}`),desc:val(`#v838-nc-desc-${i}`),state:val(`#v838-nc-state-${i}`)||'Open',days:Number(val(`#v838-nc-days-${i}`))||0,blocking:$(`#v838-nc-block-${i}`)?.checked||false})).filter(n=>n.id||n.desc);
  const selected=val('#tm-plan-type')||'No Change', reason=val('#tm-plan-reason').trim();
  if(original){let type=selected;const shipChanged=oldShip!==t.ship,qChanged=oldQ!==t.quarter;if(type==='No Change'&&(shipChanged||qChanged)){if(qChanged){let oi=-1,ni=-1;try{oi=QUARTERS.indexOf(oldQ);ni=QUARTERS.indexOf(t.quarter)}catch(e){}type=(oi>=0&&ni>=0&&ni<oi)?'Pull In':(oi>=0&&ni>oi)?'Push Out':'Quarter Change'}else type='Ship Date Change'}if(shipChanged||qChanged){t.originalShip=t.originalShip||oldShip;t.originalQuarter=t.originalQuarter||oldQ;t.changeHistory=t.changeHistory||[];t.changeHistory.unshift({field:'MFG Ship / Quarter',oldValue:`${oldShip} · ${oldQ}`,newValue:`${t.ship} · ${t.quarter}`,type,reason,changedAt:new Date().toISOString()});if(type==='Pull In'){t.pullIn=t.ship;t.pulledInFrom=oldQ;t.pushOut='';t.nextQuarter=''}else if(type==='Push Out'){t.pushOut=t.ship;t.nextQuarter=t.quarter;t.pullIn='';t.pulledInFrom=''}}}
  else {t.originalShip=t.ship;t.originalQuarter=t.quarter}
  return t;
}
function renderMaster(id,requestedSection){
  const original=id?toolById(id):null, t=original?JSON.parse(JSON.stringify(original)):newTool();
  t.changeHistory=t.changeHistory||[];t.ncs=t.ncs||[];t.leadAdmin=t.leadAdmin||{};t.checklistStates=t.checklistStates||{};t.schedule=t.schedule||{publish:'N/A',status:'N/A',subsystems:'',cables:'',accessories:'',mst:'N/A',is:'',notes:''};
  purple(id?`TOOL ${id}`:'ADD TOOL');remember({kind:'masterTool',id:id?String(id):'',section:requestedSection||''});
  const appEl=$('#app');if(!appEl)return;
  appEl.innerHTML=`<div class="report-screen v838-master-tool"><section class="v838-master-head"><div><span>${original?'MASTER TOOL RECORD':'NEW TOOL RECORD'}</span><h2>${esc(id||'ADD TOOL')}</h2><small>${esc(t.codename||'')} · ${esc(t.model||'')} · ${esc(t.customer||'')}</small></div><div><b>${esc(t.quarterStatus||'Waiting for FI')}</b><small>${esc(t.ship||'Ship date not set')}</small></div></section>
  <section class="panel v838-section" id="tool-section-overview"><h3>Tool Information / Plan</h3><div class="form-grid"><div class="form-group"><label>Product Family</label><input value="29XX" disabled></div><div class="form-group"><label>Code Name</label><select id="tm-code">${codeOpts(t)}</select></div><div class="form-group"><label>Model</label><select id="tm-model">${modelOpts(t)}</select></div>${input('UTID','tm-id',t.id)}${input('Sales Order','tm-so',t.so)}${input('Customer','tm-customer',t.customer)}<div class="form-group"><label>Cleanroom</label><select id="tm-room">${select(['CR1','CR2','CR3'],t.room||'CR1')}</select></div>${input('Cleanroom Bay','tm-bay',t.bay)}<div class="form-group"><label>Tool Status</label><select id="tm-status">${select(['Waiting for FI','In FI','Shipped','Archive'],t.quarterStatus||'Waiting for FI')}</select></div>${input('Tool Assignment','tm-driver',t.driver)}${input('MFG Ship Date','tm-ship',t.ship,'date')} ${input('SW Version','tm-sw',t.sw)}<div class="form-group"><label>FI Process</label><select id="tm-process">${select(['Full Process','Reduced Process'],t.process||'Full Process')}</select></div>${input('Lamp Hours','tm-lamp',t.lamp,'number')}${textarea('Notes','tm-notes',t.notes)}${textarea('Latest Status','tm-activity',t.activity)}</div>
  <div class="v838-subsection"><h4>Quarter / Ship Plan</h4><p class="helper">This record is the source of truth for Tool Countdown, Shipping Center, Operations Center and Live Status.</p><div class="form-grid"><div class="form-group"><label>Current Quarter</label><select id="tm-quarter">${quarterOpts(t.quarter||qFromDate(t.ship)||currentQuarter())}</select></div><div class="form-group"><label>Plan Change Type</label><select id="tm-plan-type">${select(['No Change','Ship Date Change','Pull In','Push Out'], 'No Change')}</select></div>${input('Original MFG Ship Date','tm-original-ship',t.originalShip||t.ship,'date','disabled')}${input('Original Quarter','tm-original-quarter',t.originalQuarter||t.quarter||qFromDate(t.ship),'text','disabled')}${textarea('Plan Change Reason / Notes','tm-plan-reason','')}</div></div></section>
  <section class="panel v838-section" id="tool-section-fi"><div class="subsection-title"><h3>FI Testing / Micro Schedule</h3><div class="metric-inline">FI ${routePct(t)}%</div></div><div class="form-grid"><div class="form-group"><label>Current FI Checklist</label><select id="tm-check">${routeOpts(t)}</select><small>Authoritative FI position used throughout Command Center.</small></div><div class="form-group"><label>Micro Schedule Target</label><select id="tm-micro"><option value="">Target Not Set</option>${routeOpts({...t,checklist:t.microTargetChecklist||''})}</select><small>Where FI should be according to the micro schedule.</small></div><div class="form-group"><label>Escalation Meeting</label><select id="tm-escalation">${select(['N/A','Yes'],t.escalationMeeting||'N/A')}</select></div><div class="form-group"><label>POA</label><select id="tm-poa">${select(['N/A','Completed latest POA','Performing latest POA'],t.poa||'N/A')}</select></div><div class="form-group"><label>FI Status</label><select id="tm-fistatus">${select(['Progressing','Performing POA','Line Down'],t.fiStatus||'Progressing')}</select></div>${textarea('Waivers','tm-waivers',t.waivers)}</div><h4>Ordered FI Checklist Route</h4>${routeHtml(t)}</section>
  <section class="panel v838-section" id="tool-section-lead"><div class="subsection-title"><h3>Lead / Admin</h3><div class="metric-inline">${leadPct(t)}%</div></div><div class="form-grid"><div class="form-group wide"><label>Current Lead / Admin Task</label><select id="tm-lead-current">${leadMasterOpts(t)}</select><small>Authoritative Lead/Admin position used by the Command Center. Detailed task statuses below are supporting lead tracking only.</small></div></div>${leadHtml(t)}</section>
  <section class="panel v838-section" id="tool-section-customer"><h3>Customer Requirements</h3><div class="form-grid"><div class="form-group"><label>Customer Source Required</label><select id="tm-source-required">${select(['TBD','Yes','No'],t.sourceRequired||'TBD')}</select></div><div class="form-group"><label>Source Status</label><select id="tm-source-status">${select(['Not Started','Preparing','Pre-Source In Progress','Ready for CA','With CA Team','Source Complete','Returned to FI'],t.sourceStatus||'Not Started')}</select></div>${input('CA Handoff','tm-source-handoff',t.sourceHandoff,'date')}${input('Source Start','tm-source-start',t.sourceStart,'date')}${input('Source Complete','tm-source-complete',t.sourceComplete,'date')}<div class="form-group"><label>STR Required</label><select id="tm-str-required">${select(['TBD','Yes','No'],t.strRequired||'TBD')}</select></div><div class="form-group"><label>STR Status</label><select id="tm-str-status">${select(['Not Started','Requirements Pending','Requirements Received','Testing','Submitted to CA','Customer Approval Pending','Complete'],t.strStatus||'Not Started')}</select></div>${input('STR Due Before','tm-str-due',t.strDue,'date')}${textarea('STR Notes','tm-str-notes',t.strNotes)}</div></section>
  <section class="panel v838-section" id="tool-section-shipping"><h3>Shipping / Packing</h3><p class="helper">Shipping Center reads these values automatically. Edit the Tool here; Shipping Center is the multi-tool display.</p><div class="form-grid"><div class="form-group"><label>Publish Status</label><select id="tm-sch-pub">${select(['N/A','Draft','Published','Complete'],t.schedule.publish||'N/A')}</select></div><div class="form-group"><label>Ship Schedule</label><select id="tm-sch-status">${select(['N/A','Not Started','In Progress','Updated','Completed'],t.schedule.status||'N/A')}</select></div>${input('Subsystems Handoff','tm-sch-sub',t.schedule.subsystems,'date')}${input('Cable Kit Handoff','tm-sch-cables',t.schedule.cables,'date')}${input('Accessories Handoff','tm-sch-acc',t.schedule.accessories,'date')}${mstIsApplicable(t)?input('MST Install','tm-sch-mst',t.schedule.mst==='N/A'?'':t.schedule.mst,'date'):`<div class="form-group"><label>MST Install</label><input value="N/A — Not required for ${esc(t.codename)}" disabled><input id="tm-sch-mst" type="hidden" value="N/A"></div>`}${input('IS Handoff','tm-sch-is',t.schedule.is,'date')}${textarea('Shipping Notes','tm-sch-notes',t.schedule.notes)}</div></section>
  <section class="panel v838-section" id="tool-section-ncs"><div class="subsection-title"><h3>NCs / Escalations</h3><button type="button" id="v838AddNc" class="btn">+ Add NC</button></div><div id="v838NcList">${ncRows(t)}</div></section>
  <section class="panel v838-section" id="tool-section-history"><h3>Tool Plan Change History</h3>${historyHtml(t)}</section>
  <section class="panel v838-admin-note"><b>Custom Fields</b><span>Field definitions and configuration are managed in Administration Center.</span></section></div>`;
  const code=$('#tm-code');if(code)code.onchange=()=>{const m=$('#tm-model');if(m){try{m.innerHTML=modelOptions(code.value,'')}catch(e){}}};
  function bindNc(){ $$('.v838-remove-nc').forEach(b=>b.onclick=()=>{collect(t,original);t.ncs.splice(Number(b.dataset.i),1);renderMasterDraft(t,original,requestedSection)}); }
  $('#v838AddNc').onclick=()=>{collect(t,original);t.ncs.push({id:'',desc:'',state:'Open',days:0,blocking:false});renderMasterDraft(t,original,'ncs')};bindNc();
  function saveMaster(){collect(t,original);if(!t.id)return alert('UTID is required.');const arr=getTools();if(!original&&arr.some(x=>String(x.id)===String(t.id)))return alert('That UTID already exists.');if(t.quarterStatus==='Archive'&&!t.archiveDate)t.archiveDate=new Date().toISOString().slice(0,10);const normalized=normalizeTool(t);if(original){const idx=arr.findIndex(x=>String(x.id)===String(original.id));if(idx>=0)arr[idx]=normalized}else arr.push(normalized);try{save()}catch(e){console.error(e)};renderMaster(t.id)}
  function deleteMaster(){if(!original)return;if(!confirm(`Delete Tool ${original.id}?`))return;try{tools=tools.filter(x=>String(x.id)!==String(original.id));save()}catch(e){return alert('Could not delete tool.')}try{setView('toolcenter')}catch(e){}}
  toolbar([btn(`← BACK TO ${currentQuarter()} TOOLS`,()=>{try{setView('toolcenter')}catch(e){}})], [btn('SAVE TOOL',saveMaster,true),original?btn('DELETE TOOL',deleteMaster,false,true):null,btn('SCREENSHOT',shot),btn('REPORT',report)]);
  if(requestedSection){setTimeout(()=>document.getElementById(`tool-section-${requestedSection}`)?.scrollIntoView({block:'start'}),40)}
}
function renderMasterDraft(t,original,section){
  /* Preserve draft data by temporarily presenting it as the source object without saving. */
  const tempId=t.id||'__NEW__';const arr=getTools(),existingIndex=arr.findIndex(x=>String(x.id)===String(tempId));let inserted=false,backup=null;
  if(existingIndex>=0){backup=arr[existingIndex];arr[existingIndex]=t}else{arr.push(t);inserted=true}
  renderMaster(t.id||'',section);
  if(inserted)arr.pop();else arr[existingIndex]=backup;
}
/* Canonical route: overwrite BOTH the lexical global function binding and window property.
   Older Operations code calls toolStatus directly, so window-only overrides are insufficient. */
window.toolStatus=renderMaster;window.toolAdmin=renderMaster;
try{toolStatus=renderMaster}catch(e){}
try{toolAdmin=renderMaster}catch(e){}
/* Shipping deep links target the shipping section of the same master Tool page. */
window.B7OpenMasterTool=function(id,section){renderMaster(id,section)};
/* Any later legacy click handler can still call the canonical functions above. */
function restore(){stamp();let r=null;try{r=location.hash.length>2?JSON.parse(decodeURIComponent(location.hash.slice(1))):JSON.parse(sessionStorage.getItem('b7.route')||'null')}catch(e){}if(r?.kind==='masterTool')renderMaster(r.id||undefined,r.section||'')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(restore,320),{once:true});else setTimeout(restore,320);
stamp();
})();
