/* B7 FI Command Center v0.80.33 — final framework/navigation stabilization */
(function(){
'use strict';
window.VERSION=window.B7_APP_VERSION||'0.80.33';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const COLORS={home:['#176FA8','23,111,168','OPERATIONS CENTER'],tool:['#8E5AE8','142,90,232','TOOL CENTER'],shipping:['#27AE60','39,174,96','SHIPPING CENTER'],priority:['#D4A72C','212,167,44','PRIORITY CENTER'],status:['#F28C28','242,140,40','STATUS CENTER'],meeting:['#19B9D1','25,185,209','MEETING CENTER'],action:['#E54848','229,72,72','ACTION CENTER'],reference:['#E94A9A','233,74,154','REFERENCE CENTER'],search:['#4F6BFF','79,107,255','SEARCH CENTER'],admin:['#A6AFBC','166,175,188','ADMINISTRATION CENTER']};
function center(){return document.body.dataset.center||'home'}
function theme(){const c=COLORS[center()]||COLORS.home;['--center-color','--accent','--page-accent','--fleet-accent','--live-page-accent'].forEach(v=>{document.documentElement.style.setProperty(v,c[0]);document.body.style.setProperty(v,c[0])});['--center-rgb','--accent-rgb','--page-accent-rgb','--fleet-rgb','--live-page-rgb'].forEach(v=>{document.documentElement.style.setProperty(v,c[1]);document.body.style.setProperty(v,c[1])});const t=$('#headerPageTitle');if(t)t.textContent=c[2];const v=$('#appVersionLabel');if(v)v.textContent='B7 FI COMMAND CENTER v0.67.0';$$('.main-nav .nav-btn').forEach(b=>{const m={home:'home',toolcenter:'tool',shipping:'shipping',priorities:'priority',statuscenter:'status',meetingcenter:'meeting',actions:'action',referencecenter:'reference',searchcenter:'search'};b.classList.toggle('active',m[b.dataset.view]===center())})}
function make(label,fn,cls=''){const b=document.createElement('button');b.type='button';b.className='btn '+cls;b.textContent=label;b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();fn&&fn()});return b}
function screenshot(){try{if(typeof window.enterScreenshot==='function')return window.enterScreenshot()}catch(e){}document.body.classList.add('screenshot-mode');const x=$('#screenshotExit');if(x)x.style.display='block'}
function report(){if(typeof window.print==='function')window.print()}
function ensureActionLabel(){/* v0.70: Action Status label is rendered atomically by the ticker owner. */}
function ensureFooter(){const f=$('footer.v57-footer');if(!f)return;if(!f.querySelector('.v66-footer-left')){f.innerHTML=`<div class="v66-footer-left"><button id="administrationCenterFooter" class="v57-admin-footer-btn">ADMINISTRATION CENTER</button><strong id="appVersionLabel">B7 FI COMMAND CENTER v0.67.0</strong></div><div class="v66-footer-center"><img src="assets/kla-plus-official.png" alt="KLA+" class="v66-footer-kla"></div><div class="v66-footer-right"><div><b>COMMAND CENTER</b> <span id="opsSync">Local Production Mode · SharePoint live sync pending</span></div><div>Building 7 · Final Integration · Operations</div></div>`}const a=$('#administrationCenterFooter');if(a)a.onclick=()=>window.setView('admincenter')}
function ensureFleet(){if(window.B7AlertEngine817)return;const bar=$('#operationsBar');if(!bar)return;if(!bar.querySelector('.v65-fleet-label')){const ticker=$('#opsTickerText')?.textContent||'Loading fleet status…',tasks=$('#opsTaskCount')?.textContent||'0 open actions',presence=$('#opsPresence')?.textContent||'Context: fleet overview';bar.innerHTML=`<div class="v65-fleet-label"><b>FLEET STATUS</b></div><div class="ops-ticker v65-fleet-ticker"><span id="opsTickerText">${ticker}</span></div><div class="ops-summary v65-fleet-summary"><span id="opsTaskCount">${tasks}</span><span class="ops-divider">•</span><span id="opsPresence">${presence}</span></div>`}}
function normalizeToolbar(){const bar=$('#floatingActions');if(!bar)return;bar.style.display='flex';bar.style.pointerEvents='auto';
  if(center()==='home'){ $$(':scope > button',bar).forEach(b=>{if(/^OVERVIEW$/i.test((b.textContent||'').trim())) b.remove()}); }
  if(center()==='search')$$(':scope > button',bar).forEach(b=>{if(/^ALL RESULTS$/i.test((b.textContent||'').trim()))b.remove()});
  if(!document.body.classList.contains('v61-focused-editor')){
    let shot=$$(':scope > button',bar).find(b=>/^SCREENSHOT$/i.test((b.textContent||'').trim()));if(!shot){shot=make('SCREENSHOT',screenshot,'v67-page-action');bar.appendChild(shot)}
    let rep=$$(':scope > button',bar).find(b=>/^REPORT$/i.test((b.textContent||'').trim()));if(!rep){rep=make('REPORT',report,'v67-page-action');bar.appendChild(rep)}
  }
  const all=$$(':scope > button',bar);all.forEach(b=>{b.disabled=false;b.style.pointerEvents='auto';b.style.textTransform='uppercase';b.classList.remove('v67-page-nav','v67-page-action','v67-first-action');if(b.dataset.v57tab)b.classList.add('v67-page-nav');else b.classList.add('v67-page-action')});
  const nav=all.filter(b=>b.dataset.v57tab),acts=all.filter(b=>!b.dataset.v57tab);const shot=acts.find(b=>/^SCREENSHOT$/i.test((b.textContent||'').trim())),rep=acts.find(b=>/^REPORT$/i.test((b.textContent||'').trim())),other=acts.filter(b=>b!==shot&&b!==rep);
  const desired=[...nav,...other,shot,rep].filter(Boolean);const current=$$(':scope > button',bar);if(desired.length===current.length&&desired.some((b,i)=>b!==current[i]))desired.forEach(b=>bar.appendChild(b));
  const first=other[0]||shot||rep;if(first)first.classList.add('v67-first-action');
  if(document.body.classList.contains('v61-focused-editor')){const a=$$(':scope > button',bar),cancel=a.find(b=>/^CANCEL$/i.test(b.textContent||'')),save=a.find(b=>/^SAVE CHANGES$/i.test(b.textContent||''));if(cancel&&save){cancel.classList.add('v67-first-action');if(cancel.nextElementSibling!==save){bar.append(cancel,save)}}}
}
function fixMeeting(){if(center()!=='meeting'||document.body.classList.contains('v61-focused-editor'))return;const bar=$('#floatingActions');if(!bar)return;const bodyStart=$('#app .start-now51');const source=$$('#app button').find(b=>/START MEETING NOW/i.test(b.textContent||''));let start=$$(':scope > button',bar).find(b=>/START (NEW )?MEETING/i.test(b.textContent||''));if(!start&&source){start=make('START NEW MEETING',()=>source.click(),'v67-page-action');bar.appendChild(start)}if(start)start.textContent='START NEW MEETING';if(bodyStart)bodyStart.remove()}
function fixReference(){if(center()!=='reference'||document.body.classList.contains('v61-focused-editor'))return;const bar=$('#floatingActions');if(!bar)return;$$(':scope > button',bar).forEach(b=>{const t=(b.textContent||'').trim();if(!b.dataset.v57tab&&!/ADD REFERENCE NOTE|SCREENSHOT|REPORT/i.test(t))b.remove()});const src=$$('#app button').find(b=>/ADD REFERENCE NOTE/i.test(b.textContent||''));if(src&&!$$(':scope > button',bar).some(b=>/ADD REFERENCE NOTE/i.test(b.textContent||''))){bar.appendChild(make('ADD REFERENCE NOTE',()=>src.click(),'v67-page-action'));src.style.display='none'}}
function fixStatus(){/* v0.70: preserve original button handlers; shared toolbar normalizer only reorders existing controls. */}
function stabilize(){theme();ensureActionLabel();ensureFleet();ensureFooter();fixMeeting();fixReference();fixStatus();normalizeToolbar();$$('.main-nav .nav-btn,#floatingActions button').forEach(b=>b.style.textTransform='uppercase')}
const priorSet=window.setView;window.setView=function(v){const r=priorSet(v);setTimeout(stabilize,0);setTimeout(stabilize,50);return r};
$$('.main-nav .nav-btn').forEach(b=>b.onclick=()=>window.setView(b.dataset.view));
/* v0.70: no Action Status DOM mutation observer; ticker owns the complete bar atomically. */
setTimeout(stabilize,260);
})();
