/* B7 FI Command Center v0.80.20 — independent permanent status shell + Action Center stabilization */
(function(){
'use strict';
const VERSION='0.80.20';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const viewerOnly=()=>document.body?.dataset?.liveViewerOnly==='true';
let leadTimer=null,systemTimer=null,leadIndex=0,systemIndex=0,lastLead='',lastSystem='';
let cardSnapshots=new WeakMap();
const colors={red:'critical',orange:'attention',yellow:'reminder',blue:'information',green:'normal'};
const labels={critical:'CRITICAL',attention:'ATTENTION',reminder:'REMINDER',information:'INFORMATION',normal:'NORMAL'};
function nowISO(){return new Date().toISOString()}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function ensureState(){window.state=window.state||{};state.actionDisplay=state.actionDisplay||{};state.actionFirstSeen=state.actionFirstSeen||{};state.manualReminders=Array.isArray(state.manualReminders)?state.manualReminders:[];state.actionHistory=Array.isArray(state.actionHistory)?state.actionHistory:[]}
function keyOf(a){return String(a?.id||`auto:${a?.toolId||'general'}:${String(a?.text||'').replace(/\s+/g,' ').slice(0,180)}`)}
function defaultCtl(a){return {show:true,seconds:a?.severity==='red'?15:a?.severity==='orange'?10:a?.severity==='blue'?6:8,order:999,assignee:'',pin:false,ack:false,displayUntil:'while-open'}}
function ctl(k,a){ensureState();return state.actionDisplay[k]||(state.actionDisplay[k]=defaultCtl(a))}
function ageDays(k){const x=state.actionFirstSeen?.[k];if(!x)return 0;return Math.max(0,Math.floor((Date.now()-new Date(x).getTime())/86400000))}
function sev(a,k,d){if(d.forceSeverity)return d.forceSeverity;let s=a?.severity||'yellow';const manual=String(k).startsWith('manual:')||a?.source==='manual'||a?.manual;if(manual)return s;const age=ageDays(k);if(s==='yellow'&&age>=2)s='red';else if(s==='yellow'&&age>=1)s='orange';else if(s==='orange'&&age>=1)s='red';return s}
function rawAlerts(){try{return typeof window.v3Alerts==='function'?(window.v3Alerts()||[]):[]}catch(e){return[]}}
function leadQueue(){ensureState();return rawAlerts().map(a=>{const k=keyOf(a),d=ctl(k,a);return {...a,_k:k,_d:d,_sev:sev(a,k,d)}}).filter(a=>{const d=a._d;if(a.complete||d.show===false)return false;if(d.displayUntil&&d.displayUntil!=='while-open'&&/^\d{4}-\d{2}-\d{2}$/.test(d.displayUntil)&&today()>d.displayUntil)return false;return true}).sort((a,b)=>(Number(b._d.pin)-Number(a._d.pin))||((Number(a._d.order)||999)-(Number(b._d.order)||999))||(({red:0,orange:1,yellow:2,blue:3}[a._sev]??4)-({red:0,orange:1,yellow:2,blue:3}[b._sev]??4)))}
function systemQueue(){let list=[];try{list=typeof window.fleetStatusEntries==='function'?(window.fleetStatusEntries()||[]):[]}catch(e){}return list.map(x=>{const t=String(x.text||'');let s='blue',m=t.match(/BEHIND\s+(\d+)\s+CHECKLIST/i);if(/BLOCKING|CRITICAL/i.test(t)||(m&&Number(m[1])>=4))s='red';else if(m)s='orange';else if(/TARGET NOT SET|AT RISK|OVERDUE/i.test(t))s='yellow';else if(/ON SCHEDULE|SHIPPED|COMPLETE/i.test(t))s='green';else if(/AHEAD/i.test(t))s='blue';return {...x,_sev:s}})}
function shell(){let stack=$('#b7StatusStack');if(stack)return stack;stack=document.createElement('div');stack.id='b7StatusStack';stack.className='b7s-stack';stack.innerHTML=`<div id="b7LeadAlertsBar" class="b7s-bar" data-severity="normal"><div class="b7s-left"><span class="b7s-lamp"></span><div class="b7s-copy"><strong class="b7s-title">LEAD ALERTS</strong><span class="b7s-severity">NORMAL</span></div></div><div class="b7s-message"><span>NO ACTIVE LEAD ALERTS</span></div><div class="b7s-count">0 OPEN</div></div><div id="b7SystemStatusBar" class="b7s-bar" data-severity="normal"><div class="b7s-left"><span class="b7s-lamp"></span><div class="b7s-copy"><strong class="b7s-title">SYSTEM STATUS</strong><span class="b7s-severity">NORMAL</span></div></div><div class="b7s-message"><span>ALL ACTIVE SYSTEMS NORMAL</span></div><div class="b7s-count">0 OPEN</div></div>`;return stack}
function mount(){const s=shell();if(document.body.classList.contains('v802-live-status')){const m=$('#v802StatusMount');if(m&&s.parentElement!==m)m.appendChild(s);if(viewerOnly())$('#v802Exit')?.remove()}else{const nav=$('.sticky-header>.main-nav');const header=$('.sticky-header');if(nav&&header){if(s.parentElement!==header||s.previousElementSibling!==nav)nav.insertAdjacentElement('afterend',s)}}return s}
function setBar(id,severity,message,count){const b=$('#'+id);if(!b)return;const sk=colors[severity]||'normal';b.dataset.severity=sk;b.querySelector('.b7s-severity').textContent=labels[sk]||'NORMAL';b.querySelector('.b7s-message span').textContent=String(message||'');b.querySelector('.b7s-count').textContent=String(count||'')}
function renderLead(reset=false){clearTimeout(leadTimer);mount();const q=leadQueue();if(reset)leadIndex=0;if(!q.length){leadIndex=0;lastLead='';setBar('b7LeadAlertsBar','green','NO ACTIVE LEAD ALERTS','0 OPEN');syncDiag(q);return}leadIndex=((leadIndex%q.length)+q.length)%q.length;const a=q[leadIndex];lastLead=a._k;setBar('b7LeadAlertsBar',a._sev,a.text||'LEAD ALERT',`← OPEN ${leadIndex+1} OF ${q.length}`);syncDiag(q);const ms=Math.max(3,Math.min(60,Number(a._d.seconds)||8))*1000;leadTimer=setTimeout(()=>{const n=leadQueue();if(!n.length){renderLead(true);return}const p=n.findIndex(x=>x._k===lastLead);leadIndex=((p<0?leadIndex:p)+1)%n.length;renderLead(false)},ms)}
function renderSystem(reset=false){clearTimeout(systemTimer);mount();const q=systemQueue();if(reset)systemIndex=0;if(!q.length){systemIndex=0;lastSystem='';setBar('b7SystemStatusBar','green','ALL ACTIVE SYSTEMS NORMAL','0 OPEN');return}systemIndex=((systemIndex%q.length)+q.length)%q.length;const a=q[systemIndex];lastSystem=`${a.toolId||''}|${a.text||''}`;setBar('b7SystemStatusBar',a._sev,a.text||'SYSTEM STATUS',`← OPEN ${systemIndex+1} OF ${q.length}`);systemTimer=setTimeout(()=>{const n=systemQueue();if(!n.length){renderSystem(true);return}const p=n.findIndex(x=>`${x.toolId||''}|${x.text||''}`===lastSystem);systemIndex=((p<0?systemIndex:p)+1)%n.length;renderSystem(false)},8000)}
function refreshAll(reset=true){mount();renderLead(reset);renderSystem(reset);setVersion();enhanceActions()}
window.B7StatusEngine820={refreshAll,renderLead,renderSystem,leadQueue,systemQueue,mount};

function setVersion(){window.VERSION=VERSION;document.title=viewerOnly()?`B7 FI Live Status v${VERSION}`:`B7 FI Command Center v${VERSION}`;const v=$('#appVersionLabel');if(v)v.textContent=`B7 FI COMMAND CENTER V${VERSION}`}
function toast(t){let x=$('#b7xToast');if(!x){x=document.createElement('div');x.id='b7xToast';document.body.appendChild(x)}x.textContent=t;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),2200)}
function cardKey(card){return String(card?.dataset?.auto51||'')}
function isManual(card){const k=cardKey(card);return k.startsWith('manual:')||/\bMANUAL\b/i.test(card.querySelector('.auto-open51 small')?.textContent||'')}
function serialized(card){return JSON.stringify({assignee:card.querySelector('.ac-owner51')?.value.trim()||'',show:(card.querySelector('.ac-show51')?.value||'on')==='on',seconds:Number(card.querySelector('.ac-sec51')?.value)||8,order:Number(card.querySelector('.ac-order51')?.value)||999,pin:!!card.querySelector('.ac-pin51')?.checked,ack:!!card.querySelector('.ac-ack51')?.checked,mode:card.querySelector('.ac-until-mode51')?.value||'while-open',custom:card.querySelector('.ac-until51')?.value||''})}
function persist(card){const k=cardKey(card);if(!k)return false;ensureState();const v=JSON.parse(serialized(card)),d=state.actionDisplay[k]||defaultCtl({});Object.assign(d,{assignee:v.assignee,show:v.show,seconds:v.seconds,order:v.order,pin:v.pin,ack:v.ack,displayUntil:v.mode==='while-open'?'while-open':v.mode==='today'?today():(v.custom||'while-open')});state.actionDisplay[k]=d;card.classList.toggle('b7x-off',!d.show);card.classList.remove('b7x-dirty');cardSnapshots.set(card,serialized(card));return true}
function saveNow(){try{window.save?.()}catch(e){}renderLead(true);renderSystem(false);syncDiag()}
function deleteManual(card){if(!isManual(card))return;const k=cardKey(card),id=k.startsWith('manual:')?k.slice(7):k;if(!confirm('Permanently delete this manually-created alert/task? This cannot be undone.'))return;state.manualReminders=(state.manualReminders||[]).filter(r=>String(r.id)!==String(id));delete state.actionDisplay?.[k];delete state.actionDisplay?.[id];delete state.actionFirstSeen?.[k];try{window.save?.()}catch(e){}toast('Manual alert deleted');rerenderActions();renderLead(true)}
function resolveManual(card){if(!isManual(card))return;const k=cardKey(card),id=k.startsWith('manual:')?k.slice(7):k,r=(state.manualReminders||[]).find(x=>String(x.id)===String(id));if(!r)return;const note=prompt('Optional resolution note:','');if(note===null)return;state.actionHistory=Array.isArray(state.actionHistory)?state.actionHistory:[];state.actionHistory.unshift({...JSON.parse(JSON.stringify(r)),historyId:'hist'+Date.now(),resolvedAt:nowISO(),resolutionNote:note});r.complete=true;r.resolvedAt=nowISO();try{window.save?.()}catch(e){}toast('Manual alert resolved and moved to history');rerenderActions();renderLead(true)}
function actionButtons(card){card.querySelector('.b7x-card-actions')?.remove();const controls=card.querySelector('.auto-controls51');if(!controls)return;const row=document.createElement('div');row.className='b7x-card-actions';row.innerHTML=`<span class="b7x-card-note">${isManual(card)?'MANUAL · USER CONTROLLED':'AUTO · CLEARS ONLY FROM TOOL / WORKFLOW'}</span><span class="b7x-dirty-note">UNSAVED CHANGES</span>`;const save=document.createElement('button');save.className='btn small primary b7x-save';save.type='button';save.textContent='SAVE CHANGES';save.onclick=e=>{e.preventDefault();if(!card.classList.contains('b7x-dirty')){toast('No changes to save');return}persist(card);saveNow();toast('Saved 1 changed alert')};row.appendChild(save);if(isManual(card)){const res=document.createElement('button');res.className='btn small b7x-resolve';res.type='button';res.textContent='RESOLVE';res.onclick=e=>{e.preventDefault();if(card.classList.contains('b7x-dirty'))persist(card);resolveManual(card)};row.appendChild(res);const del=document.createElement('button');del.className='btn small b7x-delete';del.type='button';del.textContent='DELETE';del.onclick=e=>{e.preventDefault();deleteManual(card)};row.appendChild(del)}controls.appendChild(row)}
function syncDiag(q=leadQueue()){let host=$('#b7xQueueDiag');if(!host){const summary=$('.action-summary-grid');if(summary){host=document.createElement('div');host.id='b7xQueueDiag';summary.insertAdjacentElement('afterend',host)}}if(!host)return;const c={red:0,orange:0,yellow:0,blue:0};q.forEach(x=>c[x._sev]=(c[x._sev]||0)+1);host.innerHTML=`<strong>ACTIVE LEAD ALERTS: ${q.length}</strong> · Critical ${c.red||0} · Attention ${c.orange||0} · Reminder ${c.yellow||0} · Information ${c.blue||0}`}
function enhanceActions(){if(document.body.dataset.center!=='action')return;ensureState();$$('.auto-action51[data-auto51]').forEach(card=>{card.querySelectorAll('.v819-card-actions').forEach(x=>x.remove());const d=state.actionDisplay[cardKey(card)]||defaultCtl({});const show=card.querySelector('.ac-show51');if(show)show.value=d.show===false?'off':'on';card.classList.toggle('b7x-off',d.show===false);actionButtons(card);cardSnapshots.set(card,serialized(card));card.classList.remove('b7x-dirty')});syncDiag();const saveAll=$('#v815SaveAll');if(saveAll){saveAll.textContent='SAVE ALL CHANGES';saveAll.onclick=e=>{e.preventDefault();const dirty=$$('.auto-action51.b7x-dirty[data-auto51]');if(!dirty.length){toast('No changes to save');return}dirty.forEach(persist);try{window.save?.()}catch(err){}renderLead(true);renderSystem(false);syncDiag();toast(`Saved ${dirty.length} changed alert${dirty.length===1?'':'s'}`)}}}
function rerenderActions(){if(window.B7Renderers58?.actionCenter){window.B7Renderers58.actionCenter();setTimeout(enhanceActions,0)}else if(typeof window.setView==='function'){window.setView('actions');setTimeout(enhanceActions,0)}}
if(!document.documentElement.dataset.b7xDirtyBound){document.documentElement.dataset.b7xDirtyBound='1';const dirty=e=>{const card=e.target.closest?.('.auto-action51[data-auto51]');if(!card||!e.target.closest('.auto-controls51'))return;const snap=cardSnapshots.get(card);if(snap!==undefined)card.classList.toggle('b7x-dirty',serialized(card)!==snap)};document.addEventListener('input',dirty);document.addEventListener('change',dirty);document.addEventListener('click',e=>{if(e.target.closest('#v815SaveAll,.b7x-save,.b7x-delete,.b7x-resolve'))setTimeout(()=>{renderLead(true);syncDiag()},80)})}

/* Wrap navigation after all legacy patches. The fixed shell is remounted after every view change. */
const oldSetView=window.setView;if(typeof oldSetView==='function')window.setView=function(v){const out=oldSetView.apply(this,arguments);[0,80,250].forEach(ms=>setTimeout(()=>{mount();renderLead(ms===0);renderSystem(ms===0);if(v==='actions')enhanceActions();setVersion()},ms));return out};
function boot(){ensureState();setVersion();[0,100,350,900].forEach(ms=>setTimeout(()=>{mount();renderLead(ms===0);renderSystem(ms===0);enhanceActions();setVersion()},ms))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.addEventListener('storage',()=>{refreshAll(true)});
})();
