/* B7 FI Command Center v0.80.60 — Daily Workflow Stabilization + Center Lockdown
   Final authority for global active-center state and secondary page toolbar.
   Left = page/view navigation. Right = contextual actions. No duplicate toolbar writers.
*/
(function(){'use strict';
const VERSION='0.80.60';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
window.B7_APP_VERSION=VERSION; window.VERSION=VERSION;
const legacySetView=window.setView, legacyToolStatus=window.toolStatus, legacyToolAdmin=window.toolAdmin;
const COLORS={
 home:['OPERATIONS CENTER','#2477ad','36,119,173'], tool:['UPDATE CENTER','#8e5ae8','142,90,232'],
 shipping:['SHIPPING CENTER','#27ae60','39,174,96'], priority:['PRIORITY CENTER','#d4a72c','212,167,44'],
 status:['STATUS CENTER','#f28c28','242,140,40'], meeting:['MEETING CENTER','#f28c28','242,140,40'],
 action:['ACTION CENTER','#ef4b4b','239,75,75'], reference:['REFERENCE CENTER','#e94a9a','233,74,154'],
 search:['SEARCH CENTER','#536dfe','83,109,254']
};
let nav={center:'home',view:'home',mode:'view',toolId:null,meeting:'LEADS MEETING'};
let savedAction=null, deleteAction=null, observer=null, applying=false;
function q(){try{return String(window.getB7ActiveQuarter?.()||window.quarterLabel?.()||'CY26Q3').toUpperCase()}catch(e){return'CY26Q3'}}
function allTools(){try{return Array.isArray(window.tools)?window.tools:(Array.isArray(tools)?tools:[])}catch(e){return[]}}
function shot(){try{return window.enterScreenshotMode?.()}catch(e){}try{return window.enterScreenshot?.()}catch(e){}window.print()}
function report(){try{return window.openReport530?.()}catch(e){}window.print()}
function saveStore(){try{return window.save?.()}catch(e){try{return save()}catch(_){}}}
function callAdmin(section){try{if(typeof window.admin==='function')return window.admin(section);if(typeof admin==='function')return admin(section)}catch(e){}}
function btn(label,fn,active=false,danger=false){const b=document.createElement('button');b.type='button';b.className='btn'+(active?' primary':'')+(danger?' danger':'');b.textContent=label;b.onclick=e=>{e.preventDefault();e.stopPropagation();fn?.()};return b}
function desiredToolbar(){
 const L=[],R=[]; const add=(a,b)=>{a.forEach(x=>L.push(x));b.forEach(x=>R.push(x))};
 if(nav.center==='home'){add([], [btn(nav.toolId?`OPEN TOOL ${nav.toolId}`:'OPEN TOOL —',()=>nav.toolId&&window.toolStatus?.(nav.toolId)),btn('SCREENSHOT',shot),btn('REPORT',report)]);}
 else if(nav.center==='tool'){
  add([btn(`${q()} TOOLS`,()=>go('tool','tools'),nav.view==='tools'),btn('TOOL COUNTDOWN',()=>go('tool','countdown'),nav.view==='countdown'),btn('TOOL ARCHIVE',()=>go('tool','archive'),nav.view==='archive')],[]);
  if(nav.mode==='edit')R.push(btn('SAVE TOOL',()=>savedAction?.(),true),btn('CANCEL',()=>nav.toolId?window.toolStatus(nav.toolId):go('tool','tools')),nav.toolId?btn('DELETE TOOL',()=>deleteAction?.(),false,true):null);
  else if(nav.view==='archive')R.push(btn('ARCHIVE TOOL',()=>startArchiveMode(),true),btn('SCREENSHOT',shot),btn('REPORT',report));
  else if(nav.view==='detail')R.push(btn('EDIT TOOL',()=>window.toolAdmin?.(nav.toolId),true),btn('SCREENSHOT',shot),btn('REPORT',report));
  else R.push(btn('ADD TOOL',()=>window.toolAdmin?.(),true),btn('SCREENSHOT',shot),btn('REPORT',report));
 }
 else if(nav.center==='shipping'){
  if(nav.mode==='edit')add([], [btn('SAVE',()=>savedAction?.(),true),btn('CANCEL',()=>go('shipping','shipping'))]);
  else add([], [btn('EDIT SHIP SCHEDULE',openShippingChooser,true),btn('SCREENSHOT',shot),btn('REPORT',report)]);
 }
 else if(nav.center==='priority'){
  add([btn('WEEKDAY PRIORITIES',()=>go('priority','weekday'),nav.view==='weekday'),btn('WEEKEND PRIORITIES',()=>go('priority','weekend'),nav.view==='weekend')],[]);
  if(nav.mode==='edit')R.push(btn('SAVE',()=>savedAction?.(),true),btn('CANCEL',()=>go('priority',nav.view)));
  else R.push(btn(nav.view==='weekend'?'EDIT WEEKEND PRIORITIES':'EDIT WEEKDAY PRIORITIES',()=>editPriority(nav.view),true),btn('SCREENSHOT',shot),btn('REPORT',report));
 }
 else if(nav.center==='status'){
  add([btn('WEEKDAY MORNING STATUS',()=>go('status','weekday'),nav.view==='weekday'),btn('LEADS EXTRA STATUS',()=>go('status','extra'),nav.view==='extra'),btn('WEEKEND MORNING STATUS',()=>go('status','weekend'),nav.view==='weekend')],[]);
  if(nav.mode==='edit')R.push(btn('SAVE',()=>savedAction?.(),true),btn('CANCEL',()=>go('status',nav.view)));
  else R.push(btn(nav.view==='extra'?'EDIT LEADS EXTRA STATUS':nav.view==='weekend'?'EDIT WEEKEND MORNING STATUS':'EDIT WEEKDAY MORNING STATUS',()=>editStatus(nav.view),true),btn('SCREENSHOT',shot),btn('REPORT',report));
 }
 else if(nav.center==='meeting'){
  const meetings=['MORNING MEETING','WEEKEND MORNING MEETING','LEADS MEETING','ORB MEETING','FE OPTIONS MEETING','CELL MEETING']; meetings.forEach(m=>L.push(btn(m,()=>selectMeeting(m),nav.meeting===m)));
  if(nav.mode==='edit')R.push(btn('SAVE',()=>savedAction?.(),true),btn('CANCEL',()=>go('meeting','history')));
  else R.push(btn(`START ${nav.meeting}`,()=>startMeeting(nav.meeting),true),btn('SCREENSHOT',shot),btn('REPORT',report));
 }
 else if(nav.center==='action'){
  if(nav.mode==='edit')add([], [btn('SAVE',()=>savedAction?.(),true),btn('CANCEL',()=>go('action','actions'))]);
  else add([], [btn('ADD ALERT',openAddAlert,true),btn('SCREENSHOT',shot),btn('REPORT',report)]);
 }
 else if(nav.center==='reference'){
  add([btn('FI KNOWLEDGE',()=>go('reference','knowledge'),nav.view==='knowledge'),btn('REFERENCE FILES',()=>go('reference','files'),nav.view==='files')],[]);
  if(nav.mode==='edit')R.push(btn('SAVE',()=>savedAction?.(),true),btn('CANCEL',()=>go('reference',nav.view)));
  else if(nav.view==='files')R.push(btn('LOAD FILE',loadReferenceFile,true),btn('SCREENSHOT',shot),btn('REPORT',report));
  else R.push(btn('ADD REFERENCE NOTE',addReferenceNote,true),btn('SCREENSHOT',shot),btn('REPORT',report));
 }
 else if(nav.center==='search') add([], [btn('SCREENSHOT',shot),btn('REPORT',report)]);
 return [L.filter(Boolean),R.filter(Boolean)];
}
function signature(nodes){return nodes.map(b=>b.textContent.trim()).join('|')}
function expectedSig(){const [l,r]=desiredToolbar();return signature(l)+'||'+signature(r)}
function actualSig(){const bar=$('#floatingActions');if(!bar)return'';const l=bar.querySelector('.v860-left'),r=bar.querySelector('.v860-right');if(!l||!r)return'legacy';return signature($$('button',l))+'||'+signature($$('button',r))}
function applyToolbar(){if(applying)return;const bar=$('#floatingActions');if(!bar)return;const [L,R]=desiredToolbar(),want=signature(L)+'||'+signature(R);if(actualSig()===want)return;applying=true;bar.className='floating-actions page-toolbar v860-toolbar';bar.innerHTML='';const l=document.createElement('div'),r=document.createElement('div');l.className='v860-left';r.className='v860-right';L.forEach(b=>l.appendChild(b));R.forEach(b=>r.appendChild(b));bar.append(l,r);applying=false}
function setVisual(center){const [name,color,rgb]=COLORS[center]||COLORS.home;document.body.dataset.center=center==='tool'?'toolfinal':center;document.body.dataset.theme=center==='tool'?'toolcenter':center;document.documentElement.style.setProperty('--page-accent',color);document.documentElement.style.setProperty('--page-accent-rgb',rgb);document.documentElement.style.setProperty('--center-color',color);document.documentElement.style.setProperty('--center-rgb',rgb);const title=$('#headerPageTitle');if(title){let t=name;if(['home','tool','shipping','priority','status','meeting','reference','search'].includes(center))t+=` — ${q()}`;if(center==='tool'&&nav.view==='archive')t='TOOL ARCHIVE';if(center==='tool'&&nav.mode==='edit'&&nav.toolId)t=`TOOL ${nav.toolId} — EDIT`;title.textContent=t}const map={home:'home',tool:'toolcenter',shipping:'shipping',priority:'priorities',status:'statuscenter',meeting:'meetingcenter',action:'actions',reference:'referencecenter',search:'searchcenter'};$$('.main-nav .nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===map[center]));}
function settle(){setVisual(nav.center);applyToolbar();}
function after(ms=0){setTimeout(settle,ms)}
function callLegacy(v){return typeof legacySetView==='function'?legacySetView.call(window,v):undefined}
function go(center,view){nav={...nav,center,view,mode:'view',toolId:null};window.scrollTo(0,0);let out;
 if(center==='home')out=callLegacy('home');
 else if(center==='tool')out=callLegacy(view==='countdown'?'countdown':view==='archive'?'archive':'toolcenter');
 else if(center==='shipping')out=callLegacy('shipping');
 else if(center==='priority')out=callLegacy(view==='weekend'?'weekend':'priorities');
 else if(center==='status'){if(view==='extra'){renderLeadsExtra(false);out=null}else out=callLegacy('statuscenter');}
 else if(center==='meeting')out=callLegacy('meetingcenter');
 else if(center==='action')out=callLegacy('actions');
 else if(center==='reference')out=callLegacy(view==='files'?'references':'referencecenter');
 else if(center==='search')out=callLegacy('searchcenter');
 [0,30,120,350,900].forEach(after); if(center==='meeting')setTimeout(()=>prepareMeetingBody(),40); if(center==='status'&&view==='extra')setTimeout(()=>renderLeadsExtra(false),30); if(center==='status'&&view==='weekend')setTimeout(()=>clickSecondary('WEEKEND MORNING STATUS'),70); if(center==='priority')setTimeout(()=>enhancePriorityDate(view),80); if(center==='tool')setTimeout(()=>enhanceUpdateCenter(),80); return out;}
function clickSecondary(label){const b=$$('#floatingActions button').find(x=>x.textContent.trim().toUpperCase()===label);if(b&&!b.closest('.v860-toolbar'))b.click()}
function captureButton(re){return $$('#floatingActions button').find(b=>re.test(b.textContent.trim()))||$$('#app button').find(b=>re.test(b.textContent.trim()))}
function editPriority(kind){nav.mode='edit';callAdmin(kind==='weekend'?'weekend':'daily');setTimeout(()=>{const s=$('#savePriority')||captureButton(/^SAVE.*PRIORIT/i);savedAction=()=>{s?.click();setTimeout(()=>go('priority',kind),30)};settle()},10)}
function statusStore(){let st;try{st=window.state||state}catch(e){st={}};st.leadsExtraStatus=st.leadsExtraStatus||{date:new Date().toISOString().slice(0,10),notes:{},extras:[],updatedAt:''};return st.leadsExtraStatus}
function renderLeadsExtra(edit=false){setVisual('status');nav={...nav,center:'status',view:'extra',mode:edit?'edit':'view'};const x=statusStore(),list=toolOrder(),app=$('#app');if(!app)return;const rows=list.map((t,i)=>{const id=String(t.id||t.utid),alias=t.alias||'';return `<tr data-extra-tool="${esc(id)}"><td>${i+1}</td><td><b>${esc(id)}</b>${alias?`<small> · ${esc(alias)}</small>`:''}</td><td>${esc(t.room||'—')}</td><td>${edit?`<textarea rows="2">${esc(x.notes[id]||'')}</textarea>`:esc(x.notes[id]||'').replace(/\n/g,'<br>')}</td></tr>`}).join('');const extra=(x.extras||[]).map((e,i)=>`<tr data-extra-manual="${i}"><td>+</td><td>${edit?`<input class="v860-extra-label" value="${esc(e.label||'GENERAL')}">`:esc(e.label||'GENERAL')}</td><td>—</td><td>${edit?`<textarea rows="2">${esc(e.notes||'')}</textarea>`:esc(e.notes||'').replace(/\n/g,'<br>')}</td></tr>`).join('');app.innerHTML=`<div class="v860-extra-status report-screen"><section class="panel v860-status-date"><label>STATUS DATE <input id="v860ExtraDate" type="date" value="${esc(x.date||'')}"></label><h2>LEADS EXTRA STATUS — ${esc(x.date||'')}</h2>${edit?'<button id="v860AddExtra" class="btn">+ ADD ITEM</button>':''}</section><div class="table-wrap"><table class="report-table"><thead><tr><th>#</th><th>UTID / ALIAS</th><th>CLEANROOM</th><th>EXTRA STATUS / NOTES</th></tr></thead><tbody>${rows}${extra}</tbody></table></div></div>`;if(edit){$('#v860AddExtra').onclick=()=>{x.extras.push({label:'GENERAL',notes:''});saveStore();renderLeadsExtra(true)};savedAction=()=>{$$('[data-extra-tool]').forEach(r=>x.notes[r.dataset.extraTool]=r.querySelector('textarea')?.value||'');$$('[data-extra-manual]').forEach(r=>{const i=Number(r.dataset.extraManual);x.extras[i]={label:r.querySelector('.v860-extra-label')?.value||'GENERAL',notes:r.querySelector('textarea')?.value||''}});x.date=$('#v860ExtraDate')?.value||x.date;x.updatedAt=new Date().toISOString();saveStore();renderLeadsExtra(false)};}else{$('#v860ExtraDate').disabled=true}applyToolbar()}
function editStatus(kind){nav.mode='edit';if(kind==='weekday'){callAdmin('meeting');setTimeout(()=>{const s=$('#saveMorning51Top')||$('#saveMorning')||captureButton(/^SAVE.*MORNING/i);savedAction=()=>{s?.click();setTimeout(()=>go('status','weekday'),80)};setVisual('status');applyToolbar()},20);return}if(kind==='extra'){renderLeadsExtra(true);return}go('status','weekend');setTimeout(()=>{const e=$$('#app button').find(b=>/EDIT WEEKEND MORNING STATUS/i.test(b.textContent));if(e)e.click();nav.mode='edit';const s=$$('#app button').find(b=>/^SAVE$/i.test(b.textContent));savedAction=()=>{s?.click();setTimeout(()=>go('status','weekend'),40)};settle()},80)}
function openShippingChooser(){nav.mode='edit';const list=allTools().filter(t=>String(t.quarterStatus||t.status||'').toLowerCase()!=='archive').sort((a,b)=>String(a.ship||'9999').localeCompare(String(b.ship||'9999'))),app=$('#app');if(!app)return;app.innerHTML=`<div class="v855-picker panel"><h2>EDIT SHIP SCHEDULE</h2><p>Choose a tool to edit its master shipping schedule.</p><select id="v855ShipPick">${list.map(t=>`<option value="${esc(t.id||t.utid)}">${esc(t.id||t.utid)} — ${esc(t.codename||'')} ${esc(t.model||'')} — ${esc(t.customer||'')}</option>`).join('')}</select></div>`;savedAction=()=>{const id=$('#v855ShipPick')?.value;if(id)window.toolAdmin?.(id,'shipping')};applyToolbar()}
function meetingState(){let st;try{st=window.state||state}catch(e){st={}};st.meetingCenter=st.meetingCenter||{};st.meetingCenter.records=Array.isArray(st.meetingCenter.records)?st.meetingCenter.records:[];return st.meetingCenter}
function activeTools(){return allTools().filter(t=>!['archive','archived'].includes(String(t.quarterStatus||t.status||'').toLowerCase()))}
function toolOrder(){let st;try{st=window.state||state}catch(e){st={}};const order=Array.isArray(st.morningToolOrder)?st.morningToolOrder:[];return activeTools().slice().sort((a,b)=>{const ai=order.indexOf(String(a.id||a.utid)),bi=order.indexOf(String(b.id||b.utid));return (ai<0?999:ai)-(bi<0?999:bi)||String(a.id||a.utid).localeCompare(String(b.id||b.utid))})}
function fmtMeetingTime(iso){try{return new Date(iso).toLocaleString([],{weekday:'short',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})}catch(e){return iso||''}}
function prepareMeetingBody(){setVisual('meeting');renderMeetingHistory();applyToolbar()}
function renderMeetingHistory(){const app=$('#app');if(!app)return;const recs=meetingState().records.slice().sort((a,b)=>String(b.startedAt||'').localeCompare(String(a.startedAt||'')));const key=nav.meeting;app.innerHTML=`<div class="v860-meeting-center"><section class="panel v860-meeting-intro"><h2>MEETING HISTORY / MINUTES</h2><p class="gray">Select a meeting type above to start a new meeting. Saved meetings remain as historical records.</p></section><section class="panel v860-meeting-history">${recs.map(r=>`<details class="v860-meeting-record"><summary><b>${esc(r.title||'Meeting')}</b><span>${esc(fmtMeetingTime(r.startedAt))} · ${(r.actions||[]).length} actions</span></summary><div class="v860-meeting-record-body">${r.notes?`<p>${esc(r.notes).replace(/\n/g,'<br>')}</p>`:''}${r.toolNotes?Object.entries(r.toolNotes).filter(([,v])=>String(v||'').trim()).map(([id,v])=>`<div><b>${esc(id)}</b><p>${esc(v).replace(/\n/g,'<br>')}</p></div>`).join(''):''}</div></details>`).join('')||'<div class="notice">No Meeting Center history yet.</div>'}</section></div>`}
function selectMeeting(m){nav.meeting=m;nav.mode='view';renderMeetingHistory();settle()}
function startMeeting(m){const mc=meetingState(),rec={id:'meet'+Date.now(),title:m,templateId:m.toLowerCase().replace(/\s+/g,'-'),startedAt:new Date().toISOString(),updatedAt:new Date().toISOString(),notes:'',toolNotes:{},actions:[]};mc.records.unshift(rec);saveStore();nav.mode='edit';renderMeetingEditor(rec)}
function renderMeetingEditor(rec){setVisual('meeting');const app=$('#app');if(!app)return;const orb=/ORB MEETING/i.test(rec.title), toolBased=orb||/MORNING MEETING|WEEKEND MORNING MEETING/i.test(rec.title);const tools=toolOrder();app.innerHTML=`<div class="v860-meeting-editor"><section class="panel v860-meeting-header"><div><h2>${esc(rec.title)}</h2><div class="v860-timestamp">Started ${esc(fmtMeetingTime(rec.startedAt))}</div></div></section><section class="panel"><label class="v860-note-label">GENERAL NOTES<textarea id="v860GeneralNotes" rows="5" placeholder="General meeting notes…">${esc(rec.notes||'')}</textarea></label></section>${toolBased?`<section class="v860-tool-note-list">${tools.map(t=>{const id=String(t.id||t.utid),alias=t.alias||'';return `<article class="panel v860-tool-note" data-tool-note="${esc(id)}"><div class="v860-tool-note-head"><div><b>${esc(id)}</b>${alias?` <span>· ${esc(alias)}</span>`:''}<span> · ${esc(t.codename||'')} ${esc(t.model||'')} · ${esc(t.room||'')}</span></div><button class="btn small" data-open-meet-tool="${esc(id)}">OPEN TOOL</button></div><textarea rows="4" placeholder="Notes for ${esc(id)}…">${esc(rec.toolNotes?.[id]||'')}</textarea></article>`}).join('')}</section>`:''}<section class="panel v860-meet-action"><select id="v860MeetTool"><option value="">General / No Tool</option>${tools.map(t=>`<option value="${esc(t.id||t.utid)}">${esc(t.id||t.utid)} · ${esc(t.codename||'')}</option>`).join('')}</select><input id="v860MeetAction" placeholder="Action item from this meeting"><input id="v860MeetOwner" placeholder="Assigned lead"><button id="v860AddAction" class="btn">+ ADD ACTION</button><div id="v860ActionHistory">${(rec.actions||[]).map(a=>`<div><b>${esc(a.title)}</b><span>${esc(a.toolId||'General')} · ${esc(a.assignee||'Unassigned')}</span></div>`).join('')}</div></section></div>`;$$('[data-open-meet-tool]').forEach(b=>b.onclick=()=>window.toolStatus?.(b.dataset.openMeetTool));$('#v860AddAction').onclick=()=>{const title=$('#v860MeetAction').value.trim();if(!title)return;const a={id:'ma'+Date.now(),title,toolId:$('#v860MeetTool').value,assignee:$('#v860MeetOwner').value.trim(),status:'Open',source:`Meeting: ${rec.title}`,createdAt:new Date().toISOString()};rec.actions.push(a);let st;try{st=window.state||state}catch(e){st={}};st.workspaceTasks=Array.isArray(st.workspaceTasks)?st.workspaceTasks:[];st.workspaceTasks.unshift(a);$('#v860MeetAction').value='';saveStore();renderMeetingEditor(rec)};savedAction=()=>saveMeeting(rec);applyToolbar()}
function saveMeeting(rec){rec.notes=$('#v860GeneralNotes')?.value||'';$$('[data-tool-note]').forEach(d=>{rec.toolNotes=rec.toolNotes||{};rec.toolNotes[d.dataset.toolNote]=d.querySelector('textarea')?.value||''});rec.updatedAt=new Date().toISOString();rec.endedAt=new Date().toISOString();saveStore();nav.mode='view';renderMeetingHistory();settle()}
function openAddAlert(){nav.mode='edit';const app=$('#app');if(!app)return;app.innerHTML=`<div class="panel v855-add-alert"><h2>ADD ALERT</h2><div class="form-grid"><div class="form-group"><label>Type</label><select id="v855AlertType"><option>Lead Alert</option><option>System Status Alert</option><option>Task</option><option>Reminder</option></select></div><div class="form-group"><label>Related Tool</label><select id="v855AlertTool"><option value="">General</option>${allTools().filter(t=>String(t.quarterStatus)!=='Archive').map(t=>`<option value="${esc(t.id)}">${esc(t.id)} · ${esc(t.codename)}</option>`).join('')}</select></div><div class="form-group wide"><label>Message</label><input id="v855AlertMsg"></div><div class="form-group"><label>Owner</label><input id="v855AlertOwner"></div><div class="form-group"><label>Due Date</label><input id="v855AlertDue" type="date"></div></div></div>`;savedAction=saveManualAlert;applyToolbar()}
function saveManualAlert(){const msg=$('#v855AlertMsg')?.value.trim();if(!msg)return alert('Message is required.');let st;try{st=window.state||state}catch(e){st={}};st.workspaceTasks=Array.isArray(st.workspaceTasks)?st.workspaceTasks:[];const type=$('#v855AlertType')?.value||'Lead Alert';st.workspaceTasks.unshift({id:'manual-'+Date.now(),title:msg,toolId:$('#v855AlertTool')?.value||'',assignee:$('#v855AlertOwner')?.value.trim()||'',due:$('#v855AlertDue')?.value||'',status:'Open',priority:type==='System Status Alert'?'Critical':'Normal',source:`Manual ${type}`,createdAt:new Date().toISOString(),showTicker:true,alertType:type});saveStore();go('action','actions')}
function addReferenceNote(){const underlying=$$('#app button').find(b=>/ADD REFERENCE NOTE/i.test(b.textContent)&&!b.closest('#floatingActions'));if(underlying){underlying.click();nav.mode='edit';setTimeout(()=>{const s=$$('#app button').find(b=>/^SAVE/i.test(b.textContent));savedAction=()=>{s?.click();setTimeout(()=>go('reference','knowledge'),30)};applyToolbar()},20)}}
function loadReferenceFile(){if(nav.view!=='files')return;const choice=prompt('Load reference file:\n1 = Local file\n2 = Shared / network URL','1');if(choice==='2'){const url=prompt('Paste the shared/network file URL:','');if(url)showReferenceSource(url,'Shared / network file','url');return}if(choice!=='1')return;let input=$('#v860RefFile');if(!input){input=document.createElement('input');input.id='v860RefFile';input.type='file';input.hidden=true;document.body.appendChild(input);input.onchange=()=>{const f=input.files?.[0];if(!f)return;showReferenceLocal(f)}}input.value='';input.click()}
function referenceViewer(){let page=$('#app .v854-file-page');if(!page){const app=$('#app');if(!app)return null;app.innerHTML='<div class="v854-file-page v860-reference-page"><div class="v854-file-meta" id="v854FileMeta">No reference file loaded.</div><div class="v854-file-viewer" id="v854FileViewer"></div></div>';page=$('#app .v854-file-page')}return {meta:$('#v854FileMeta'),viewer:$('#v854FileViewer')}}
function showReferenceLocal(f){const x=referenceViewer();if(!x)return;const url=URL.createObjectURL(f),ext=(f.name.split('.').pop()||'').toLowerCase(),inline=['pdf','png','jpg','jpeg','gif','webp','txt','html','htm'].includes(ext);x.meta.innerHTML='<b>Loaded:</b> '+esc(f.name)+' <span class="gray">· Local file</span>';if(inline){if(['png','jpg','jpeg','gif','webp'].includes(ext))x.viewer.innerHTML=`<img class="v860-ref-image" src="${url}" alt="${esc(f.name)}">`;else if(ext==='txt'){f.text().then(t=>x.viewer.innerHTML=`<pre class="v860-ref-text">${esc(t)}</pre>`)}else x.viewer.innerHTML=`<iframe title="Reference File Viewer" src="${url}"></iframe>`}else{x.viewer.innerHTML=`<div class="v860-file-fallback"><h3>${esc(f.name)}</h3><p>This file type cannot be reliably previewed inside the browser.</p><a class="btn primary" href="${url}" target="_blank" rel="noopener">OPEN FILE</a><button class="btn" id="v860CloseFile">CLOSE FILE</button></div>`;$('#v860CloseFile').onclick=()=>{x.meta.textContent='No reference file loaded.';x.viewer.innerHTML='<div class="gray">Use LOAD FILE to open a local file or shared/network URL.</div>'}}}
function showReferenceSource(url,name,kind){const x=referenceViewer();if(!x)return;x.meta.innerHTML='<b>Loaded:</b> '+esc(name)+' <span class="gray">· Shared / network URL</span>';x.viewer.innerHTML=`<iframe title="Reference File Viewer" src="${esc(url)}"></iframe><div class="v860-file-fallback v860-url-fallback"><p>If the network site blocks embedded viewing, open it directly.</p><a class="btn primary" href="${esc(url)}" target="_blank" rel="noopener">OPEN FILE</a></div>`}
function weekRange(value){if(!value)return'';const d=new Date(value+'T12:00:00'),day=(d.getDay()+6)%7,m=new Date(d);m.setDate(d.getDate()-day);const f=new Date(m);f.setDate(m.getDate()+4);const fmt=x=>x.toLocaleDateString([],{month:'short',day:'numeric',year:'numeric'});return `${fmt(m)} – ${fmt(f)}`}
function enhancePriorityDate(kind){if(nav.center!=='priority')return;const app=$('#app');if(!app)return;let st;try{st=window.state||state}catch(e){st={}};st.priorityDates=st.priorityDates||{};const key=kind==='weekend'?'weekend':'weekday';let panel=$('#v860PriorityDate');if(!panel){panel=document.createElement('section');panel.id='v860PriorityDate';panel.className='panel v860-priority-date';app.prepend(panel)}const current=st.priorityDates[key]||new Date().toISOString().slice(0,10);panel.innerHTML=key==='weekday'?`<label>WEEK DATE <input id="v860PriDate" type="date" value="${esc(current)}"></label><strong id="v860PriTitle">B7 WEEKDAY PRIORITIES — ${esc(weekRange(current))}</strong>`:`<label>WEEKEND DATE <input id="v860PriDate" type="date" value="${esc(current)}"></label><strong id="v860PriTitle">B7 WEEKEND PRIORITIES</strong>`;$('#v860PriDate').onchange=e=>{st.priorityDates[key]=e.target.value;saveStore();if(key==='weekday')$('#v860PriTitle').textContent='B7 WEEKDAY PRIORITIES — '+weekRange(e.target.value)}}
function enhanceUpdateCenter(){if(nav.center!=='tool')return;$('.main-nav [data-view="toolcenter"]')?.replaceChildren(document.createTextNode('UPDATE CENTER'));const title=$('#headerPageTitle');if(title&&/TOOL CENTER/.test(title.textContent))title.textContent=title.textContent.replace('TOOL CENTER','UPDATE CENTER');$$('#app h1,#app h2,#app h3').forEach(h=>{if(/^TOOL CENTER/i.test(h.textContent))h.textContent=h.textContent.replace(/^TOOL CENTER/i,'UPDATE CENTER')})}
function addAliasToToolEditor(){if(nav.center!=='tool'||nav.mode!=='edit')return;const root=$('#app');if(!root||root.querySelector('.v860-alias-field'))return;const id=nav.toolId,t=allTools().find(x=>String(x.id||x.utid)===String(id));const labels=$$('label',root),utidLabel=labels.find(l=>/UTID/i.test(l.textContent));if(!utidLabel)return;const wrap=document.createElement('label');wrap.className='v860-alias-field';wrap.innerHTML=`Alias / Shop-floor shorthand<input id="v860Alias" value="${esc(t?.alias||'')}" placeholder="Optional, e.g. RG71">`;utidLabel.insertAdjacentElement('afterend',wrap);const orig=savedAction;savedAction=()=>{if(t)t.alias=$('#v860Alias')?.value.trim()||'';saveStore();orig?.()};applyToolbar()}
function startArchiveMode(){nav.mode='edit';const app=$('#app');if(!app)return;const list=allTools().filter(t=>String(t.quarterStatus||t.status||'').toLowerCase()!=='archive');app.innerHTML=`<div class="panel v855-archive-mode"><h2>ARCHIVE TOOL</h2><div class="table-wrap"><table class="report-table"><thead><tr><th>UTID</th><th>CODE NAME</th><th>MODEL</th><th>CUSTOMER</th><th>CURRENT STATUS</th><th>NEW STATUS</th></tr></thead><tbody>${list.map(t=>`<tr><td><b>${esc(t.id||t.utid)}</b></td><td>${esc(t.codename||'—')}</td><td>${esc(t.model||'—')}</td><td>${esc(t.customer||'—')}</td><td>${esc(t.quarterStatus||t.status||'—')}</td><td><select class="v855-archive-select" data-id="${esc(t.id||t.utid)}"><option value="">No Change</option><option value="Archive">Archive</option></select></td></tr>`).join('')||'<tr><td colspan="6">No active tools available.</td></tr>'}</tbody></table></div><div id="v855ArchiveMsg"></div></div>`;savedAction=()=>{const ids=$$('.v855-archive-select').filter(x=>x.value==='Archive').map(x=>String(x.dataset.id));if(!ids.length){const m=$('#v855ArchiveMsg');if(m)m.textContent='No changes to save.';return}const day=new Date().toISOString().slice(0,10);allTools().forEach(t=>{if(ids.includes(String(t.id||t.utid))){t.quarterStatus='Archive';t.status='Archive';t.archiveDate=t.archiveDate||day}});saveStore();nav.mode='view';go('tool','archive')};applyToolbar()}
/* Global routing is capture-phase so old handlers cannot select the wrong center. */
document.addEventListener('click',e=>{const b=e.target.closest('.main-nav .nav-btn');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const v=b.dataset.view;const map={home:['home','home'],toolcenter:['tool','tools'],shipping:['shipping','shipping'],priorities:['priority','weekday'],statuscenter:['status','weekday'],meetingcenter:['meeting','history'],actions:['action','actions'],referencecenter:['reference','knowledge'],searchcenter:['search','search']};if(map[v])go(...map[v])},true);
window.setView=function(v){const map={home:['home','home'],systems:['tool','tools'],toolcenter:['tool','tools'],countdown:['tool','countdown'],archive:['tool','archive'],shipping:['shipping','shipping'],priorities:['priority','weekday'],daily:['priority','weekday'],weekend:['priority','weekend'],statuscenter:['status','weekday'],meeting:['status','weekday'],leads:['status','extra'],meetingcenter:['meeting','history'],actions:['action','actions'],referencecenter:['reference','knowledge'],references:['reference','files'],searchcenter:['search','search']};if(map[v])return go(...map[v]);return callLegacy(v)};try{setView=window.setView}catch(e){}
/* Tool detail/edit wrappers capture real Save/Delete handlers before any legacy toolbar patch can erase them. */
if(typeof legacyToolStatus==='function'){window.toolStatus=function(id){nav={...nav,center:'tool',view:'detail',mode:'view',toolId:String(id)};const out=legacyToolStatus.apply(this,arguments);[0,30,150].forEach(after);return out};try{toolStatus=window.toolStatus}catch(e){}}
if(typeof legacyToolAdmin==='function'){window.toolAdmin=function(id){nav={...nav,center:'tool',view:'tools',mode:'edit',toolId:id?String(id):null};const out=legacyToolAdmin.apply(this,arguments);const saveB=captureButton(/^SAVE TOOL$/i),delB=captureButton(/^DELETE TOOL$/i);savedAction=saveB?.onclick?saveB.onclick.bind(saveB):null;deleteAction=delB?.onclick?delB.onclick.bind(delB):null;[0,20,80,200].forEach(after);[40,140].forEach(ms=>setTimeout(addAliasToToolEditor,ms));return out};try{toolAdmin=window.toolAdmin}catch(e){}}
function installObserver(){const bar=$('#floatingActions');if(!bar)return;observer?.disconnect();observer=new MutationObserver(()=>{if(applying)return;queueMicrotask(()=>{setVisual(nav.center);if(actualSig()!==expectedSig())applyToolbar()})});observer.observe(bar,{childList:true,subtree:true,characterData:true});}
function boot(){const nb=$('.main-nav [data-view="toolcenter"]');if(nb)nb.textContent='UPDATE CENTER';document.title=`B7 FI Command Center v${VERSION}`;const v=$('#appVersionLabel');if(v)v.textContent=`B7 FI COMMAND CENTER V${VERSION}`;installObserver();const active=$('.main-nav .nav-btn.active')?.dataset.view||'home';const map={home:['home','home'],toolcenter:['tool','tools'],shipping:['shipping','shipping'],priorities:['priority','weekday'],statuscenter:['status','weekday'],meetingcenter:['meeting','history'],actions:['action','actions'],referencecenter:['reference','knowledge'],searchcenter:['search','search']};if(map[active])nav={...nav,center:map[active][0],view:map[active][1]};settle();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
