/* B7 FI Command Center v0.80.53 — Navigation / Archive workflow recovery.
   Narrow stabilization build:
   - Restores Center page navigation/action bars after v0.80.52 regression.
   - Tool Archive gets ARCHIVE TOOL -> CANCEL / SAVE bulk workflow.
   - Tool Edit keeps working CANCEL / SAVE TOOL / DELETE TOOL controls.
   - Tool Center navigation stays left, actions stay right.
   - No data-model redesign; all changes use the existing master tools[] records.
*/
(function(){'use strict';
const VERSION='0.80.53';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
window.B7_APP_VERSION=VERSION;window.VERSION=VERSION;
let routeToken=0;
function q(){try{return String(window.getB7ActiveQuarter?.()||window.quarterLabel?.()||'CY26Q3').toUpperCase()}catch(e){return'CY26Q3'}}
function toolsAll(){try{return Array.isArray(window.tools)?window.tools:(Array.isArray(tools)?tools:[])}catch(e){return[]}}
function saveAll(){try{return window.save?.()}catch(e){try{return save()}catch(_){}}}
function shot(){try{if(typeof window.enterScreenshotMode==='function')return window.enterScreenshotMode()}catch(e){}try{if(typeof window.enterScreenshot==='function')return window.enterScreenshot()}catch(e){}window.print()}
function report(){window.print()}
function btn(label,fn,primary=false,danger=false){const b=document.createElement('button');b.type='button';b.className='btn'+(primary?' primary':'')+(danger?' danger':'');b.textContent=label;b.onclick=fn;return b}
function toolbar(left=[],right=[]){const bar=$('#floatingActions');if(!bar)return;bar.className='floating-actions page-toolbar v853-toolbar';bar.innerHTML='';const l=document.createElement('div'),r=document.createElement('div');l.className='v853-nav-left';r.className='v853-actions-right';left.filter(Boolean).forEach(x=>l.appendChild(x));right.filter(Boolean).forEach(x=>r.appendChild(x));bar.append(l,r)}
function stamp(){document.title=`B7 FI Command Center v${VERSION}`;const v=$('#appVersionLabel');if(v)v.textContent=`B7 FI COMMAND CENTER V${VERSION}`}
function toolTheme(title){document.body.dataset.center='toolfinal';document.body.dataset.theme='toolcenter';document.documentElement.style.setProperty('--page-accent','#8b5cf6');document.documentElement.style.setProperty('--page-accent-rgb','139,92,246');const h=$('#headerPageTitle');if(h)h.textContent=title;$$('.main-nav .nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view==='toolcenter'))}
function toolNav(active='tools'){return [btn(`${q()} TOOLS`,()=>window.setView?.('toolcenter'),active==='tools'),btn('TOOL COUNTDOWN',()=>window.setView?.('countdown'),active==='countdown'),btn('TOOL ARCHIVE',()=>renderArchive(),active==='archive')]}
function activeTools(){return toolsAll().filter(t=>String(t.quarterStatus||t.status||'').toLowerCase()!=='archive')}
function archivedTools(){return toolsAll().filter(t=>String(t.quarterStatus||t.status||'').toLowerCase()==='archive')}
function fmt(v){if(!v)return'—';try{const s=String(v).slice(0,10),d=new Date(s+'T00:00:00');return isNaN(d)?String(v):d.toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric'})}catch(e){return String(v)}}
function openTool(id){if(typeof window.toolStatus==='function')window.toolStatus(id)}
function renderArchive(){routeToken++;toolTheme('TOOL ARCHIVE');const app=$('#app');if(!app)return;const list=archivedTools();app.innerHTML=`<div class="v853-simple-page"><div class="table-wrap"><table class="report-table v853-archive-table"><thead><tr><th>UTID</th><th>CODE NAME</th><th>MODEL</th><th>CUSTOMER</th><th>SALES ORDER</th><th>SHIP DATE</th><th>QUARTER</th><th>ARCHIVED</th></tr></thead><tbody>${list.map(t=>`<tr data-v853-tool="${esc(t.id||t.utid)}"><td><b>${esc(t.id||t.utid)}</b></td><td>${esc(t.codename||t.codeName||'—')}</td><td>${esc(t.model||'—')}</td><td>${esc(t.customer||'—')}</td><td>${esc(t.so||t.salesOrder||'—')}</td><td>${esc(fmt(t.ship||t.shipDate))}</td><td>${esc(t.quarter||'—')}</td><td>${esc(fmt(t.archiveDate))}</td></tr>`).join('')||'<tr><td colspan="8" class="gray">No archived tools.</td></tr>'}</tbody></table></div></div>`;toolbar(toolNav('archive'),[btn('ARCHIVE TOOL',renderArchiveMode,true),btn('SCREENSHOT',shot),btn('REPORT',report)]);$$('[data-v853-tool]',app).forEach(r=>r.onclick=()=>openTool(r.dataset.v853Tool))}
function renderArchiveMode(){routeToken++;toolTheme('TOOL ARCHIVE');const app=$('#app');if(!app)return;const list=activeTools();app.innerHTML=`<div class="v853-simple-page"><div class="table-wrap"><table class="report-table"><thead><tr><th>UTID</th><th>CODE NAME</th><th>MODEL</th><th>CUSTOMER</th><th>CURRENT STATUS</th><th>NEW STATUS</th></tr></thead><tbody>${list.map(t=>`<tr><td><b>${esc(t.id||t.utid)}</b></td><td>${esc(t.codename||t.codeName||'—')}</td><td>${esc(t.model||'—')}</td><td>${esc(t.customer||'—')}</td><td>${esc(t.quarterStatus||t.status||'Waiting to be Handed to FI')}</td><td><select class="v853-archive-select" data-id="${esc(t.id||t.utid)}"><option value="">No Change</option><option value="Archive">Archive</option></select></td></tr>`).join('')||'<tr><td colspan="6" class="gray">No active tools available to archive.</td></tr>'}</tbody></table></div><div id="v853ArchiveNotice" class="v853-notice" aria-live="polite"></div></div>`;toolbar(toolNav('archive'),[btn('CANCEL',renderArchive),btn('SAVE',saveArchive,true)])}
function saveArchive(){const ids=$$('.v853-archive-select').filter(s=>s.value==='Archive').map(s=>String(s.dataset.id));if(!ids.length){const n=$('#v853ArchiveNotice');if(n){n.textContent='No changes to save.';n.classList.add('show')}return}const today=new Date().toISOString().slice(0,10);toolsAll().forEach(t=>{if(ids.includes(String(t.id||t.utid))){t.quarterStatus='Archive';t.status='Archive';t.archiveDate=t.archiveDate||today}});saveAll();try{document.dispatchEvent(new CustomEvent('b7fi:tool-records-updated',{detail:{reason:'archive',ids}}))}catch(e){}renderArchive();const n=document.createElement('div');n.className='v853-ack';n.textContent=ids.length===1?`✓ Tool ${ids[0]} moved to Archive`:`✓ ${ids.length} tools moved to Archive`;$('#app')?.prepend(n);setTimeout(()=>n.remove(),4200)}
function cleanCountdown(){const app=$('#app');if(!app||!/TOOL COUNTDOWN/i.test(app.textContent||''))return;toolTheme(`TOOL CENTER — ${q()}`);$$('h1,h2,h3',app).forEach(h=>{const t=(h.textContent||'').trim();if(new RegExp(`^${q()}\\s+TOOL COUNTDOWN$`,'i').test(t)||/^TOOL COUNTDOWN$/i.test(t))h.remove()});$$('p,.helper',app).forEach(p=>{if(/Fast quarter view|Click any tool to open its master Tool page/i.test(p.textContent||''))p.remove()});toolbar(toolNav('countdown'),[btn('ADD TOOL',()=>window.toolAdmin?.(),true),btn('SCREENSHOT',shot),btn('REPORT',report)])}
function recoverToolDashboard(){toolTheme(`TOOL CENTER — ${q()}`);toolbar(toolNav('tools'),[btn('ADD TOOL',()=>window.toolAdmin?.(),true),btn('SCREENSHOT',shot),btn('REPORT',report)])}
function callAdmin(section){try{if(typeof window.admin==='function')return window.admin(section);if(typeof admin==='function')return admin(section)}catch(e){}}
function textHas(re){return re.test(String($('#app')?.textContent||''))}
function centerToolbar(view){
 const center=document.body.dataset.center||'';
 if(view==='home'||center==='home')return; // Operations owns its live-status toolbar.
 if(view==='shipping'||center==='shipping'){
   toolbar([btn(`${q()} SHIPPING`,()=>window.setView?.('shipping'),true)],[btn('EDIT SHIPPING SCHEDULES',()=>callAdmin('shipping'),true),btn('SCREENSHOT',shot),btn('REPORT',report)]);return;
 }
 if(view==='priorities'||center==='priority'){
   const weekend=textHas(/WEEKEND PRIORIT/i);toolbar([btn('WEEKDAY PRIORITIES',()=>window.setView?.('priorities'),!weekend),btn('WEEKEND PRIORITIES',()=>window.setView?.('weekend'),weekend)],[btn('EDIT PRIORITIES',()=>callAdmin(weekend?'weekend':'daily'),true),btn('SCREENSHOT',shot),btn('REPORT',report)]);return;
 }
 if(view==='statuscenter'||center==='status'){
   const extra=textHas(/LEADS EXTRA STATUS/i),weekend=textHas(/WEEKEND MORNING STATUS/i);toolbar([btn('WEEKDAY MORNING STATUS',()=>window.setView?.('statuscenter'),!extra&&!weekend),btn('LEADS EXTRA STATUS',()=>window.setView?.('leads'),extra),btn('WEEKEND MORNING STATUS',()=>renderWeekendStatus(false),weekend)],[btn(extra?'UPDATE LEADS EXTRA STATUS':weekend?'UPDATE WEEKEND MORNING STATUS':'UPDATE WEEKDAY MORNING STATUS',()=>extra?callAdmin('leads'):weekend?renderWeekendStatus(true):callAdmin('meeting'),true),btn('SCREENSHOT',shot),btn('REPORT',report)]);return;
 }
 if(view==='meetingcenter'||center==='meeting'){
   toolbar([btn('MEETING CENTER',()=>window.setView?.('meetingcenter'),true)],[btn('START NEW MEETING',()=>{const x=$('#adhocStart51')||$$('#app button').find(b=>/START.*MEETING/i.test(b.textContent||''));if(x)x.click()} ,true),btn('SCREENSHOT',shot),btn('REPORT',report)]);return;
 }
 if(view==='actions'||center==='action'){
   toolbar([btn('ACTION CENTER',()=>window.setView?.('actions'),true)],[btn('SCREENSHOT',shot),btn('REPORT',report)]);return;
 }
 if(view==='referencecenter'||center==='reference'){
   const files=textHas(/OPERATIONS REFERENCE FILES|MICRO SCHEDULE.*SHIPPING TRACKER/i);toolbar([btn('FI KNOWLEDGE',()=>window.setView?.('referencecenter'),!files),btn('REFERENCE FILES',()=>window.setView?.('references'),files)],[btn('ADD REFERENCE NOTE',()=>{const x=$$('#app button').find(b=>/ADD REFERENCE NOTE/i.test(b.textContent||''));if(x)x.click()},true),btn('SCREENSHOT',shot),btn('REPORT',report)]);return;
 }
 if(view==='searchcenter'||center==='search'){
   toolbar([btn('ALL RESULTS',()=>window.setView?.('searchcenter'),true)],[btn('SCREENSHOT',shot),btn('REPORT',report)]);return;
 }
}
function renderWeekendStatus(edit=false){document.body.dataset.center='status';document.body.dataset.theme='status';const h=$('#headerPageTitle');if(h)h.textContent=`STATUS CENTER — ${q()}`;$$('.main-nav .nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view==='statuscenter'));let st;try{st=window.state||state}catch(e){st={}};st.weekendMorningStatus=st.weekendMorningStatus||{lead:'',date:'',notes:'',updatedAt:''};const w=st.weekendMorningStatus;let list=activeTools().filter(t=>t.weekendPriority).sort((a,b)=>(a.weekendPriority||999)-(b.weekendPriority||999));const app=$('#app');if(!app)return;const rows=list.map(t=>`<tr><td>${esc(t.weekendPriority||'')}</td><td><b>${esc(t.id||t.utid)}</b></td><td>${esc(t.model||'—')}</td><td>${esc(t.customer||'—')}</td><td>${esc(fmt(t.ship||t.shipDate))}</td><td>${esc(t.weekendAssignment||t.driver||'')}</td><td>${esc(t.weekendNotes||'')}</td></tr>`).join('')||'<tr><td colspan="7">No weekend priorities assigned.</td></tr>';if(edit){app.innerHTML=`<div class="v853-simple-page"><div class="form-grid"><label>Weekend Lead<input id="v853WLead" value="${esc(w.lead)}"></label><label>Date<input id="v853WDate" type="date" value="${esc(w.date)}"></label></div><label>Weekend Status Notes<textarea id="v853WNotes" rows="7">${esc(w.notes)}</textarea></label><div class="table-wrap"><table class="report-table"><thead><tr><th>Priority</th><th>UTID</th><th>Model</th><th>Customer</th><th>Ship Date</th><th>Assignment</th><th>Notes</th></tr></thead><tbody>${rows}</tbody></table></div></div>`;toolbar([btn('WEEKDAY MORNING STATUS',()=>window.setView?.('statuscenter')),btn('LEADS EXTRA STATUS',()=>window.setView?.('leads')),btn('WEEKEND MORNING STATUS',()=>renderWeekendStatus(false),true)],[btn('CANCEL',()=>renderWeekendStatus(false)),btn('SAVE',()=>{w.lead=$('#v853WLead')?.value.trim()||'';w.date=$('#v853WDate')?.value||'';w.notes=$('#v853WNotes')?.value||'';w.updatedAt=new Date().toISOString();saveAll();renderWeekendStatus(false)},true)])}else{app.innerHTML=`<div class="v853-simple-page"><div class="panel"><div><b>${esc(w.date||'Weekend Morning Status')}</b> · Weekend Lead: ${esc(w.lead||'Not assigned')}</div>${w.notes?`<p>${esc(w.notes).replace(/\n/g,'<br>')}</p>`:''}</div><div class="table-wrap"><table class="report-table"><thead><tr><th>Priority</th><th>UTID</th><th>Model</th><th>Customer</th><th>Ship Date</th><th>Assignment</th><th>Notes</th></tr></thead><tbody>${rows}</tbody></table></div></div>`;centerToolbar('statuscenter')}}
function recoverToolEdit(id,saveFn,deleteFn){toolTheme(id?`TOOL ${id} — EDIT`:'ADD TOOL');toolbar(toolNav('tools'),[btn('CANCEL',()=>id?window.toolStatus?.(id):window.setView?.('toolcenter')),saveFn?btn('SAVE TOOL',saveFn,true):null,id&&deleteFn?btn('DELETE TOOL',deleteFn,false,true):null].filter(Boolean))}
/* Capture Save/Delete handlers synchronously before older delayed toolbar patches can discard them. */
const priorToolAdmin=window.toolAdmin;if(typeof priorToolAdmin==='function'){window.toolAdmin=function(id){const out=priorToolAdmin.apply(this,arguments);const bs=$$('#floatingActions button'),saveB=bs.find(b=>/^SAVE TOOL$/i.test((b.textContent||'').trim())),delB=bs.find(b=>/^DELETE TOOL$/i.test((b.textContent||'').trim()));const saveFn=saveB?.onclick?saveB.onclick.bind(saveB):null,delFn=delB?.onclick?delB.onclick.bind(delB):null;[10,120,350,750,1150].forEach(ms=>setTimeout(()=>recoverToolEdit(id,saveFn,delFn),ms));return out};try{toolAdmin=window.toolAdmin}catch(e){}}
/* Archive route is owned here so legacy archive renderers cannot replace it. */
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const t=(b.textContent||'').trim().toUpperCase();if(t==='TOOL ARCHIVE'){e.preventDefault();e.stopImmediatePropagation();renderArchive()}},true);
const priorSetView=window.setView;if(typeof priorSetView==='function'){window.setView=function(v){if(v==='archive'){renderArchive();return}const token=++routeToken,out=priorSetView.apply(this,arguments);const apply=()=>{if(token!==routeToken)return;if(v==='toolcenter'||v==='systems')recoverToolDashboard();else if(v==='countdown')cleanCountdown();else centerToolbar(v)};[20,120,360,760,1200].forEach(ms=>setTimeout(apply,ms));return out};try{setView=window.setView}catch(e){}}
function boot(){stamp();const active=$('.main-nav .nav-btn.active')?.dataset.view||'home';[100,500,1200].forEach(ms=>setTimeout(()=>{stamp();if(active==='toolcenter'){if(/TOOL ARCHIVE/i.test($('#headerPageTitle')?.textContent||''))renderArchive();else if(/TOOL COUNTDOWN/i.test($('#app')?.textContent||''))cleanCountdown();else if(/—\s*EDIT/i.test($('#headerPageTitle')?.textContent||'')){}else recoverToolDashboard()}else centerToolbar(active)},ms))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
