/* B7 FI Command Center v0.80.33 — Countdown Lifecycle Finalization */
(function(){
const VERSION=window.B7_APP_VERSION||'0.80.33';
function quarterOpts(sel){
  const vals=[sel,...(typeof QUARTERS!=='undefined'?QUARTERS:[]),...tools.map(t=>t.quarter),...tools.map(t=>t.originalQuarter)].filter(Boolean);
  return [...new Set(vals)].map(x=>`<option value="${esc(x)}" ${x===sel?'selected':''}>${esc(x)}</option>`).join('');
}
function cardBadges(t,q,pushed){
  let b=[],oq=t.originalQuarter||quarterFromDate(t.originalShip)||'',cq=t.quarter||quarterFromDate(t.ship)||'';
  if(String(t.process||'').toLowerCase().includes('reduced'))b.push(['reduced','REDUCED PROCESS']);
  if(t.sourceRequired==='Yes')b.push(['source','SOURCE REQUIRED']);
  if(t.strRequired==='Yes')b.push(['str','STR REQUIRED']);
  if(typeof packingActive==='function'&&packingActive(t))b.push(['packing','PACKING ACTIVE']);
  if(t.originalShip&&t.ship&&t.originalShip!==t.ship)b.push(['change','SHIP DATE CHANGED']);
  if(t.originalCustomer&&t.customer!==t.originalCustomer)b.push(['change','CUSTOMER CHANGED']);
  if(t.originalSO&&t.so!==t.originalSO)b.push(['change','SO CHANGED']);
  if(oq&&cq&&oq!==q&&cq===q)b.push(['pull','PULLED IN']);
  if(pushed||(oq===q&&cq&&cq!==q))b.push(['push','PUSHED OUT']);
  return b.map(x=>`<span class="cc-badge ${x[0]}">${x[1]}</span>`).join('');
}
function progressBar(label,value,kind,detail){value=Math.max(0,Math.min(100,Number(value)||0));return `<div class="cc-progress-row ${kind}"><div class="cc-progress-head"><span>${label}</span><b>${value}%</b></div><div class="cc-progress-track"><i style="width:${value}%"></i></div>${detail?`<div class="cc-progress-detail">${esc(detail)}</div>`:''}</div>`}
function lifecycleCard(t,q,pushed=false){
  let waiting=t.quarterStatus==='Waiting for FI',shipped=t.quarterStatus==='Shipped',packing=!shipped&&typeof packingActive==='function'&&packingActive(t),infi=!waiting&&!shipped;
  let oq=t.originalQuarter||quarterFromDate(t.originalShip)||'',cq=t.quarter||quarterFromDate(t.ship)||'',badges=cardBadges(t,q,pushed),moved=t.originalShip&&t.ship&&t.originalShip!==t.ship;
  let status=shipped?'SHIPPED':waiting?'WAITING FOR FI':packing?'PACKING':'IN FI';
  let body='';
  if(waiting){
    body=`<div class="cc-meta cc-meta-rich waiting-meta"><div><span>MFG Ship Date</span><b>${fmt(t.ship)}</b></div><div><span>Sales Order</span><b>${esc(t.so||'N/A')}</b></div></div>`;
  }else if(shipped){
    let actual=t.actualShipDate||t.ship, plan=t.originalShip||t.ship;
    body=`<div class="cc-meta cc-meta-rich shipped-meta"><div><span>Planned Ship</span><b>${fmt(plan)}</b></div><div><span>Actual Ship</span><b>${fmt(actual)}</b></div><div><span>Sales Order</span><b>${esc(t.so||'N/A')}</b></div><div><span>Completion</span><b>FI ✓${typeof packingProgress==='function'&&packingProgress(t)>=100?' · PACKING ✓':''}</b></div></div>`;
  }else if(packing){
    let pp=typeof packingProgress==='function'?packingProgress(t):0,next=typeof nextPackingHandoff==='function'?nextPackingHandoff(t):null;
    body=`<div class="cc-meta cc-meta-rich"><div><span>MFG Ship Date</span><b>${fmt(t.ship)}</b></div><div><span>Sales Order</span><b>${esc(t.so||'N/A')}</b></div><div><span>FI Testing</span><b>100% COMPLETE</b></div><div><span>Next Handoff</span><b>${esc(next?.label||'Complete')}</b></div></div>${progressBar('Packing Progress',pp,'packing-progress',next?.label||'')}`;
  }else{
    let actual=typeof routeProgress==='function'?routeProgress(t):0,mi=typeof microScheduleInfo==='function'?microScheduleInfo(t):null;
    body=`<div class="cc-meta cc-meta-rich"><div><span>MFG Ship Date</span><b>${fmt(t.ship)}</b></div><div><span>Sales Order</span><b>${esc(t.so||'N/A')}</b></div><div><span>Current Phase</span><b>${esc(typeof currentPhase==='function'?currentPhase(t):'FI TESTING')}</b></div><div><span>Current Checklist</span><b>${esc(t.checklist||'—')}</b></div></div>${progressBar('Actual FI Progress',actual,'actual-progress',t.checklist||'')}${mi&&mi.set?progressBar('Micro Schedule Target',mi.plannedPct,'micro-progress',mi.target||''):`<div class="cc-micro unset">MICRO SCHEDULE TARGET NOT SET</div>`}${mi&&mi.set?`<div class="schedule-chip ${mi.className}">${esc(mi.label)}</div>`:''}`;
  }
  let lifeClass=waiting?'life-waiting':shipped?'life-shipped':packing?'life-packing':'life-infi';
  return `<article class="countdown-card lifecycle-card ${qState(t)} ${lifeClass} ${packing?'packing-tint':''} ${pushed?'pushed-card':''}" data-open-countdown-tool="${esc(t.id)}" tabindex="0" role="button" aria-label="Open tool ${esc(t.id)}"><div class="cc-head"><div><div class="cc-id">${esc(t.id)}</div><b>${esc(t.model)}</b><div class="gray">${esc(t.customer||'N/A')}</div></div><span class="state-chip lifecycle-shape ${lifeClass}">${status}</span></div>${body}${badges?`<div class="cc-badges">${badges}</div>`:''}${moved?`<div class="quarter-movement-line"><span>${fmt(t.originalShip)} → ${fmt(t.ship)}</span><strong>${esc(oq||'—')} → ${esc(cq||'—')}</strong></div>`:''}</article>`;
}
function familyBlock(name,arr,q){let w=arr.filter(t=>t.quarterStatus==='Waiting for FI').length,i=arr.filter(t=>t.quarterStatus==='In FI').length,s=arr.filter(t=>t.quarterStatus==='Shipped').length;return `<section class="countdown-family final-family"><div class="countdown-family-head"><h2>${esc(name)}</h2><div class="family-counts"><div class="family-total"><span>TOTAL</span><b>${arr.length}</b></div><div class="family-waiting"><span>WAITING FI</span><b>${w}</b></div><div class="family-infi"><span>IN FI</span><b>${i}</b></div><div class="family-shipped"><span>SHIPPED</span><b>${s}</b></div></div></div><div class="countdown-card-grid final-countdown-grid">${arr.sort((a,b)=>(a.ship||'9').localeCompare(b.ship||'9')).map(t=>lifecycleCard(t,q)).join('')}</div></section>`}
countdown=function(){
  let q=calendarQuarter(),s=quarterMovementStats(q),sh=s.curr.filter(t=>t.quarterStatus==='Shipped').length,need=s.curr.length-sh,g={};s.curr.forEach(t=>(g[t.codename||'Other']??=[]).push(t));
  app.innerHTML=page('Quarter Tool Shipping Countdown','Quarter commitment, pull-in/push-out movement and tool-family status.','QUARTER PLAN')+`<div class="report-screen">${reportHeader(`${q} TOOL SHIPPING COUNTDOWN`)}<div class="overall-countdown v21-countdown"><div class="overall-box"><div class="label">Original Plan</div><span class="number">${s.orig.length}</span></div><div class="overall-box"><div class="label">Current Plan</div><span class="number">${s.curr.length}</span></div><div class="overall-box need"><div class="label">Need to Ship</div><span class="number">${need}</span></div><div class="overall-box shipped"><div class="label">Shipped</div><span class="number">${sh}</span></div><div class="overall-box pull"><div class="label">Pulled Into ${q}</div><span class="number">${s.pulled.length}</span></div><div class="overall-box push"><div class="label">Pushed Out</div><span class="number">${s.pushed.length}</span></div></div><div class="quarter-progress"><div class="progress-label"><span>Current Quarter Shipping Progress</span><b>${pct(sh,s.curr.length)}% Shipped</b></div><div class="track"><div class="fill" style="width:${pct(sh,s.curr.length)}%;background:var(--good)"></div></div></div><section class="panel tool-type-panel">${Object.entries(g).sort((a,b)=>a[0].localeCompare(b[0])).map(([n,a])=>familyBlock(n,a,q)).join('')}</section>${s.pushed.length?`<section class="panel movement-panel"><h3>Still in FI — Pushed Out of ${q}</h3><div class="countdown-card-grid final-countdown-grid">${s.pushed.map(t=>lifecycleCard(t,q,true)).join('')}</div></section>`:''}</div>`;
  document.querySelectorAll('[data-open-countdown-tool]').forEach(c=>{let go=()=>toolStatus(c.dataset.openCountdownTool);c.onclick=go;c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}}});
  actions([{label:'Edit Tool Countdown',primary:true,fn:()=>admin('countdown')},{label:'Tools',fn:()=>setView('systems')},{label:'Administration',fn:()=>setView('admin')}]);
};
countdownAdmin=function(){return `<div class="panel"><h3>Quarter Tool Shipping Countdown Admin · Plan Change Workflow</h3><p class="helper">Use New MFG Ship Date + New Quarter to record a Pull In or Push Out without overwriting history. Current values update only when the change is applied.</p><div class="table-wrap"><table class="report-table compact-form-table countdown-admin-table final-countdown-admin"><thead><tr><th>UTID</th><th>Code Name</th><th>Current MFG Ship</th><th>Current Quarter</th><th>Change Type</th><th>New MFG Ship Date</th><th>New Quarter</th><th>Reason / Notes</th><th>Status</th></tr></thead><tbody>${tools.map(t=>`<tr data-cd43="${esc(t.id)}"><td><b>${esc(t.id)}</b></td><td>${esc(t.codename)}</td><td><b>${fmt(t.ship)}</b><small class="admin-original">Original: ${fmt(t.originalShip)}</small></td><td><b>${esc(t.quarter||quarterFromDate(t.ship)||'—')}</b><small class="admin-original">Original: ${esc(t.originalQuarter||quarterFromDate(t.originalShip)||'—')}</small></td><td><select class="cd43-type"><option>No Change</option><option>Pull In</option><option>Push Out</option></select></td><td><input class="cd43-date" type="date" value=""></td><td><select class="cd43-quarter"><option value="">Select quarter</option>${quarterOpts(t.quarter||quarterFromDate(t.ship))}</select></td><td><input class="cd43-reason" placeholder="Customer request / plan change / etc."></td><td>${lifecycleSelect(t,'cd43-status')}</td></tr>`).join('')}</tbody></table></div><div class="actions"><button id="saveCountdown43" class="btn primary">Apply Countdown Changes</button></div></div>`};
const wire43=wireAdmin;
wireAdmin=function(s){if(s!=='countdown')return wire43(s);document.querySelectorAll('[data-cd43]').forEach(r=>{let d=r.querySelector('.cd43-date'),q=r.querySelector('.cd43-quarter');d.onchange=()=>{let v=quarterFromDate(d.value);if(v){if(![...q.options].some(o=>o.value===v))q.insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(v)}</option>`);q.value=v}}});let btn=$('#saveCountdown43');if(btn)btn.onclick=()=>{document.querySelectorAll('[data-cd43]').forEach(r=>{let t=tools.find(x=>x.id===r.dataset.cd43);if(!t)return;let type=r.querySelector('.cd43-type').value,newDate=r.querySelector('.cd43-date').value,newQ=r.querySelector('.cd43-quarter').value,reason=r.querySelector('.cd43-reason').value.trim(),status=r.querySelector('.cd43-status').value;if(type!=='No Change'&&(newDate||newQ)){let oldDate=t.ship,oldQ=t.quarter||quarterFromDate(t.ship)||'';newDate=newDate||oldDate;newQ=newQ||quarterFromDate(newDate)||oldQ;t.changeHistory=t.changeHistory||[];t.changeHistory.unshift({date:new Date().toISOString(),type:type.toUpperCase(),field:'MFG Ship / Quarter',oldValue:`${oldDate} · ${oldQ}`,newValue:`${newDate} · ${newQ}`,reason});if(typeof recordChange==='function'){recordChange(t,'Ship Date',oldDate,newDate,reason);recordChange(t,'Quarter',oldQ,newQ,reason)}t.ship=newDate;t.quarter=newQ}t.quarterStatus=status});save();setView('countdown')};};
const toolStatus43=toolStatus;toolStatus=function(id){toolStatus43(id);let t=tools.find(x=>x.id===id);if(!t)return;setTimeout(()=>{if(String(t.process||'').toLowerCase().includes('reduced')){let metrics=document.querySelector('.metric-grid');if(metrics&&!metrics.querySelector('.reduced-process-metric'))metrics.insertAdjacentHTML('beforeend','<div class="metric reduced-process-metric"><span>FI Process</span><strong>REDUCED PROCESS</strong><small>Reduced FI test route active</small></div>');let h=document.querySelector('.report-screen .report-header, .report-screen h2');if(h&&!document.querySelector('.reduced-process-banner'))h.insertAdjacentHTML('afterend','<div class="reduced-process-banner">REDUCED PROCESS ACTIVE</div>')}},0)};
document.title=`B7 FI Command Center v${VERSION}`;let v=document.getElementById('appVersionLabel');if(v)v.textContent=`B7 FI Command Center v${VERSION}`;setTimeout(()=>render(),0);
})();
