/* B7 FI Command Center v0.61.0 — Global UX / Editor / Status workflow pass */
(function(){
'use strict';
window.VERSION='0.61.0';
const COLORS={home:['#176FA8','23,111,168','OPERATIONS CENTER'],tool:['#8E5AE8','142,90,232','TOOL CENTER'],shipping:['#27AE60','39,174,96','SHIPPING CENTER'],priority:['#D4A72C','212,167,44','PRIORITY CENTER'],status:['#F28C28','242,140,40','STATUS CENTER'],meeting:['#19B9D1','25,185,209','MEETING CENTER'],action:['#E54848','229,72,72','ACTION CENTER'],reference:['#E94A9A','233,74,154','REFERENCE CENTER'],admin:['#A6AFBC','166,175,188','ADMINISTRATION CENTER']};
const qs=(s,r=document)=>r.querySelector(s), qsa=(s,r=document)=>[...r.querySelectorAll(s)];
function esc61(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function theme61(k){let c=COLORS[k]||COLORS.home;document.body.dataset.center=k;['--center-color','--accent','--page-accent','--fleet-accent','--live-page-accent'].forEach(v=>{document.documentElement.style.setProperty(v,c[0]);document.body.style.setProperty(v,c[0])});['--center-rgb','--accent-rgb','--page-accent-rgb','--fleet-rgb','--live-page-rgb'].forEach(v=>{document.documentElement.style.setProperty(v,c[1]);document.body.style.setProperty(v,c[1])});let t=qs('#headerPageTitle');if(t)t.textContent=c[2];qsa('.main-nav .nav-btn').forEach(b=>b.classList.toggle('active',({home:'home',toolcenter:'tool',shipping:'shipping',priorities:'priority',statuscenter:'status',meetingcenter:'meeting',actions:'action',referencecenter:'reference'}[b.dataset.view]===k)));let v=qs('#appVersionLabel');if(v)v.textContent='B7 FI Command Center v0.61.0'}
function bar61(buttons){let b=qs('#floatingActions');if(!b)return;b.style.display='';b.innerHTML='';buttons.forEach(x=>{let bt=document.createElement('button');bt.className='btn '+(x.primary?'primary':'')+(x.right?' v61-right':'');bt.textContent=x.label;bt.onclick=x.fn;b.appendChild(bt)})}
function returnViewFor(section){return {countdown:'toolcenter',shipping:'shipping',daily:'priorities',weekend:'weekend',meeting:'statuscenter',tools:'toolcenter',config:'admincenter'}[section]||'home'}
function centerForEdit(section){return {countdown:'tool',shipping:'shipping',daily:'priority',weekend:'priority',meeting:'status',tools:'tool',config:'admin'}[section]||'admin'}
function saveIdFor(section){return {countdown:'saveCountdown',shipping:'saveShipping',daily:'savePriority',weekend:'savePriority',meeting:'saveMorning'}[section]||''}
let legacyAdmin=window.admin;
window.admin=function(section='home'){
  if(section==='home'||section==='config') return legacyAdmin(section);
  const center=centerForEdit(section), back=returnViewFor(section);
  theme61(center);document.body.classList.add('v61-focused-editor');document.body.dataset.editorSection=section;
  app.innerHTML='<div id="adminBody" class="v61-editor-body"></div>';
  renderAdmin(section);
  let dirty=false;qsa('#app input,#app select,#app textarea').forEach(el=>{el.addEventListener('input',()=>dirty=true);el.addEventListener('change',()=>dirty=true)});
  const cancel=()=>{if(dirty&&!confirm('Discard unsaved changes?'))return;document.body.classList.remove('v61-focused-editor');delete document.body.dataset.editorSection;setView(back)};
  const saveId=saveIdFor(section);
  bar61([{label:'CANCEL',fn:cancel},{label:'SAVE CHANGES',primary:true,fn:()=>{let x=qs('#'+saveId);if(x)x.click();else alert('No save control is available for this editor.')}}]);
  qsa('.admin-tabs,.admin-launch-grid').forEach(x=>x.remove());
  decorate61();
};
let legacyToolAdmin=window.toolAdmin;
if(legacyToolAdmin)window.toolAdmin=function(id){legacyToolAdmin(id);theme61('tool');document.body.classList.add('v61-focused-editor');let b=qs('#floatingActions');if(b){qsa('button',b).forEach(x=>{if(/administration/i.test(x.textContent))x.remove()});let c=document.createElement('button');c.className='btn';c.textContent='CANCEL';c.onclick=()=>{if(confirm('Discard unsaved changes?'))setView('toolcenter')};b.prepend(c)}decorate61()};

function weekendStatus61(edit=false){theme61('status');document.body.classList.toggle('v61-focused-editor',edit);state.weekendMorningStatus=state.weekendMorningStatus||{lead:'',date:'',notes:'',updatedAt:''};let w=state.weekendMorningStatus;let wk=[...(typeof tools!=='undefined'?tools:[])].filter(t=>t.weekendPriority).sort((a,b)=>(a.weekendPriority||999)-(b.weekendPriority||999));
  if(edit){app.innerHTML=`<div class="v61-weekend-status"><h2>WEEKEND MORNING STATUS</h2><div class="v61-edit-grid"><label>Weekend Lead<input id="wmLead61" value="${esc61(w.lead)}"></label><label>Date<input id="wmDate61" type="date" value="${esc61(w.date)}"></label></div><label>Weekend Status Notes<textarea id="wmNotes61" rows="8">${esc61(w.notes)}</textarea></label><h3>Weekend Tool Priorities</h3>${weekendTable61(wk)}</div>`;let dirty=false;qsa('#app input,#app textarea').forEach(x=>x.oninput=()=>dirty=true);bar61([{label:'CANCEL',fn:()=>{if(dirty&&!confirm('Discard unsaved changes?'))return;weekendStatus61(false)}},{label:'SAVE CHANGES',primary:true,fn:()=>{w.lead=qs('#wmLead61').value.trim();w.date=qs('#wmDate61').value;w.notes=qs('#wmNotes61').value;w.updatedAt=new Date().toISOString();save();weekendStatus61(false)}}]);}
  else{app.innerHTML=`<div class="v61-weekend-status"><div class="v61-status-meta"><b>${esc61(w.date||'Weekend Morning Status')}</b><span>Weekend Lead: ${esc61(w.lead||'Not assigned')}</span>${w.updatedAt?`<span>Updated ${new Date(w.updatedAt).toLocaleString()}</span>`:''}</div>${w.notes?`<div class="v61-notes">${esc61(w.notes).replace(/\n/g,'<br>')}</div>`:''}<h3>Weekend Tool Priorities</h3>${weekendTable61(wk)}</div>`;statusNav61('weekend')}
  decorate61();
}
function weekendTable61(a){return `<div class="table-wrap"><table class="report-table"><thead><tr><th>Priority</th><th>UTID</th><th>Model</th><th>Customer</th><th>Ship Date</th><th>Assignment</th><th>Notes</th></tr></thead><tbody>${a.map(t=>`<tr><td>${t.weekendPriority||''}</td><td><b>${esc61(t.id)}</b></td><td>${esc61(t.model)}</td><td>${esc61(t.customer)}</td><td>${esc61(t.ship||'')}</td><td>${esc61(t.weekendAssignment||t.driver||'')}</td><td>${esc61(t.weekendNotes||'')}</td></tr>`).join('')||'<tr><td colspan="7">No weekend priorities assigned.</td></tr>'}</tbody></table></div>`}
function statusNav61(active){bar61([{label:'MORNING STATUS',primary:active==='morning',fn:()=>setView('statuscenter')},{label:'WEEKEND MORNING STATUS',primary:active==='weekend',fn:()=>weekendStatus61(false)},{label:'LEADS EXTRA STATUS',primary:active==='extra',fn:()=>{let b=qsa('#floatingActions [data-v57tab]');let x=b.find(y=>y.textContent.includes('LEADS'));if(x)x.click()}},{label:'EDIT WEEKEND STATUS',fn:()=>weekendStatus61(true)},{label:'REPORT',right:true,fn:()=>window.print()}])}

function actionNav61(){let b=qs('#floatingActions');if(!b)return;let sums={};qsa('.action-summary').forEach(x=>{let k=(qs('span',x)?.textContent||'').toUpperCase();sums[k]=qs('strong',x)?.textContent||'0'});bar61([{label:'ADD TASK',primary:true,fn:addTaskModal61},{label:`ALL ${Object.values(sums).reduce((a,x)=>a+(+x||0),0)}`,fn:()=>filterActions61('ALL')},{label:`CRITICAL ${sums.CRITICAL||0}`,fn:()=>filterActions61('CRITICAL')},{label:`ATTENTION ${sums.ATTENTION||0}`,fn:()=>filterActions61('ATTENTION')},{label:`REMINDERS ${sums['REMINDERS / NEXT ACTIONS']||0}`,fn:()=>filterActions61('REMINDERS')},{label:`INFORMATION ${sums.INFORMATION||0}`,fn:()=>filterActions61('INFORMATION')},{label:'REPORT',right:true,fn:()=>window.print()}])}
function filterActions61(k){qsa('.action-group').forEach(g=>{let h=(qs('h3',g)?.textContent||'').toUpperCase();g.style.display=(k==='ALL'||h.includes(k))?'':'none'})}
function addTaskModal61(){qs('#v61TaskModal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div id="v61TaskModal" class="v61-modal"><div class="v61-modal-card"><h3>ADD TASK</h3><div class="v61-edit-grid"><label>Tool<select id="v61TaskTool"><option value="">General / No Tool</option>${(typeof tools!=='undefined'?tools:[]).map(t=>`<option value="${esc61(t.id)}">${esc61(t.id)} · ${esc61(t.model)}</option>`).join('')}</select></label><label>Category<select id="v61TaskSev"><option value="yellow">Reminder</option><option value="orange">Attention</option><option value="red">Critical</option><option value="blue">Information</option></select></label></div><label>Task<input id="v61TaskText" placeholder="Task / follow-up / information"></label><div class="actions"><button class="btn" id="v61TaskCancel">CANCEL</button><button class="btn primary" id="v61TaskAdd">ADD TASK</button></div></div></div>`);qs('#v61TaskCancel').onclick=()=>qs('#v61TaskModal').remove();qs('#v61TaskAdd').onclick=()=>{let text=qs('#v61TaskText').value.trim();if(!text)return;state.manualReminders=Array.isArray(state.manualReminders)?state.manualReminders:[];state.manualReminders.unshift({id:'mr'+Date.now(),toolId:qs('#v61TaskTool').value,severity:qs('#v61TaskSev').value,text,complete:false,createdAt:new Date().toISOString()});save();qs('#v61TaskModal').remove();setView('actions')}}

function dormantToolSummary61(){if(document.body.dataset.center!=='tool')return;let boxes=qsa('#app .overall-box,#app .metric,#app .metric-card,#app .summary-card');let pulled=0,pushed=0;boxes.forEach(x=>{let tx=x.textContent.toUpperCase(),n=parseInt((tx.match(/\b\d+\b/g)||[]).slice(-1)[0]||'0',10);if(tx.includes('PULLED'))pulled=n;if(tx.includes('PUSHED'))pushed=n});boxes.forEach(x=>{let tx=x.textContent.toUpperCase();if((tx.includes('PULLED')&&pulled===0)||(tx.includes('PUSHED')&&pushed===0)||(tx.includes('UPDATED')&&pulled===0&&pushed===0))x.classList.add('v61-dormant');else x.classList.remove('v61-dormant')})}
function removeShippingHelp61(){if(document.body.dataset.center!=='shipping')return;qsa('#app .notice').forEach(x=>{if(/No systems have entered 200 Packing/i.test(x.textContent))x.remove()})}
function genericEditor61(){let saveMeet=qs('#saveMeet51');if(saveMeet&&!document.body.classList.contains('v61-focused-editor')){document.body.classList.add('v61-focused-editor');theme61('meeting');bar61([{label:'CANCEL',fn:()=>setView('meetingcenter')},{label:'SAVE CHANGES',primary:true,fn:()=>saveMeet.click()}])}}
function decorate61(){let c=document.body.dataset.center||'home';theme61(c);removeShippingHelp61();dormantToolSummary61();genericEditor61();if(c==='action'){qsa('#app section.panel').forEach(s=>{if(/Add Manual Reminder/i.test(s.textContent))s.remove()});actionNav61()}if(c==='status'&&!document.body.classList.contains('v61-focused-editor')){let bar=qs('#floatingActions');if(bar&&!qs('.v61-weekend-btn',bar)){let btn=document.createElement('button');btn.className='btn v61-weekend-btn';btn.textContent='WEEKEND MORNING STATUS';btn.onclick=()=>weekendStatus61(false);let report=qsa('button',bar).find(x=>x.textContent.trim()==='REPORT');bar.insertBefore(btn,bar.firstChild)}}}

let oldSetView=window.setView;window.setView=function(v){document.body.classList.remove('v61-focused-editor');oldSetView(v);setTimeout(decorate61,0)};
let obsBusy=false;new MutationObserver(()=>{if(obsBusy)return;obsBusy=true;requestAnimationFrame(()=>{decorate61();obsBusy=false})}).observe(document.getElementById('app'),{childList:true,subtree:false});
setTimeout(decorate61,50);
})();
