/* B7 FI Command Center v0.80.33 — single-source Alert Engine + dirty-save Action Center */
(function(){
'use strict';
const VERSION=window.B7_APP_VERSION||'0.80.33';
window.VERSION=VERSION;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const viewerOnly=document.body?.dataset?.liveViewerOnly==='true';
const STATUS={red:{key:'critical',label:'CRITICAL'},orange:{key:'attention',label:'ATTENTION'},yellow:{key:'reminder',label:'REMINDER'},blue:{key:'information',label:'INFORMATION'},green:{key:'normal',label:'NORMAL'}};
let leadTimer=null,systemTimer=null,popupTimer=null,leadIndex=0,systemIndex=0,lastLeadKey='',lastSystemKey='';
let actionSnapshots=new WeakMap();
const todayISO=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function setVersion(){document.title=viewerOnly?`B7 FI Live Status v${VERSION}`:`B7 FI Command Center v${VERSION}`;const v=$('#appVersionLabel');if(v)v.textContent=`B7 FI COMMAND CENTER V${VERSION}`}
function actionKey(a){return String(a?.id||`auto:${a?.toolId||'general'}:${String(a?.text||'').replace(/\s+/g,' ').slice(0,180)}`)}
function ensureState(){window.state=window.state||{};state.actionDisplay=state.actionDisplay||{};state.actionFirstSeen=state.actionFirstSeen||{};state.manualReminders=Array.isArray(state.manualReminders)?state.manualReminders:[];state.actionHistory=Array.isArray(state.actionHistory)?state.actionHistory:[]}
function migrateManual(){ensureState();state.manualReminders.forEach(r=>{const full='manual:'+r.id,bare=String(r.id);if(!state.actionDisplay[full]&&state.actionDisplay[bare]){state.actionDisplay[full]=state.actionDisplay[bare];delete state.actionDisplay[bare]}if(!state.actionFirstSeen[full]&&state.actionFirstSeen[bare]){state.actionFirstSeen[full]=state.actionFirstSeen[bare];delete state.actionFirstSeen[bare]}})}
function ctl(k,a){ensureState();migrateManual();let d=state.actionDisplay[k];if(!d){d=state.actionDisplay[k]={show:true,seconds:a?.severity==='red'?15:a?.severity==='orange'?10:a?.severity==='blue'?6:8,order:999,assignee:'',pin:false,ack:false,displayUntil:'while-open'}}return d}
function ageDays(k){const x=state.actionFirstSeen?.[k];return x?Math.max(0,Math.floor((Date.now()-new Date(x).getTime())/86400000)):0}
function severity(a,k,d){if(d.forceSeverity)return d.forceSeverity;let s=a?.severity||'yellow';const manual=String(k).startsWith('manual:')||a?.source==='manual'||a?.manual;if(manual)return s;const age=ageDays(k);if(s==='yellow'&&age>=2)s='red';else if(s==='yellow'&&age>=1)s='orange';else if(s==='orange'&&age>=1)s='red';return s}
function rawAlerts(){try{return typeof window.v3Alerts==='function'?(window.v3Alerts()||[]):[]}catch(e){return[]}}
function activeLeadQueue(){
  migrateManual();
  return rawAlerts().map(a=>{const k=actionKey(a),d=ctl(k,a);return {...a,_k:k,_d:d,_sev:severity(a,k,d)}}).filter(a=>{
    const d=a._d;if(a.complete||d.show===false)return false;
    if(d.displayUntil&&d.displayUntil!=='while-open'&&/^\d{4}-\d{2}-\d{2}$/.test(d.displayUntil)&&todayISO()>d.displayUntil)return false;
    return true;
  }).sort((a,b)=>(Number(b._d.pin)-Number(a._d.pin))||((Number(a._d.order)||999)-(Number(b._d.order)||999))||(({red:0,orange:1,yellow:2,blue:3}[a._sev]??4)-({red:0,orange:1,yellow:2,blue:3}[b._sev]??4)));
}
function systemQueue(){let list=[];try{list=typeof window.fleetStatusEntries==='function'?(window.fleetStatusEntries()||[]):[]}catch(e){}return list.map(x=>{const t=String(x.text||'');let s='blue',m=t.match(/BEHIND\s+(\d+)\s+CHECKLIST/i);if(/BLOCKING|CRITICAL/i.test(t)||(m&&Number(m[1])>=4))s='red';else if(m)s='orange';else if(/TARGET NOT SET|AT RISK|OVERDUE/i.test(t))s='yellow';else if(/ON SCHEDULE|SHIPPED|COMPLETE/i.test(t))s='green';else if(/AHEAD/i.test(t))s='blue';return {...x,_sev:s}})}
function ensureBar(id,title){let bar=document.getElementById(id);if(!bar){bar=document.createElement('div');bar.id=id;bar.className=id==='topActionBar'?'top-action-bar':'operations-bar'}
  const good=bar.querySelector('.v819-status-left')&&bar.querySelector('.v819-status-message')&&bar.querySelector('.v819-status-count');
  if(!good){bar.replaceChildren();const left=document.createElement('div');left.className='v819-status-left';left.innerHTML=`<span class="v819-status-lamp" aria-hidden="true"></span><div class="v819-status-copy"><strong class="v819-status-title"></strong><span class="v819-status-severity">NORMAL</span></div>`;const msg=document.createElement('button');msg.type='button';msg.className='v819-status-message';const count=document.createElement('div');count.className='v819-status-count';bar.append(left,msg,count)}
  bar.querySelector('.v819-status-title').textContent=title;return bar;
}
function paint(bar,title,sev,message,count,onClick){if(!bar)return;bar=ensureBar(bar.id,title);const info=STATUS[sev]||STATUS.green;bar.dataset.v819Severity=info.key;bar.dataset.status=info.key;bar.querySelector('.v819-status-severity').textContent=info.label;const msg=bar.querySelector('.v819-status-message');msg.textContent=String(message||'');msg.disabled=!onClick;msg.onclick=onClick||null;bar.querySelector('.v819-status-count').textContent=String(count||'')}
function mountLive(){if(!document.body.classList.contains('v802-live-status'))return;const mount=$('#v802StatusMount');if(!mount)return;const lead=ensureBar('topActionBar','LEAD ALERTS'),sys=ensureBar('operationsBar','SYSTEM STATUS');if(lead.parentElement!==mount)mount.appendChild(lead);if(sys.parentElement!==mount)mount.appendChild(sys);if(lead.nextElementSibling!==sys)mount.insertBefore(lead,sys);if(viewerOnly)$('#v802Exit')?.remove()}
function homeBars(){const stack=$('.sticky-header .header-status-stack');if(!stack||document.body.classList.contains('v802-live-status'))return;const lead=ensureBar('topActionBar','LEAD ALERTS'),sys=ensureBar('operationsBar','SYSTEM STATUS');if(lead.parentElement!==stack)stack.prepend(lead);if(sys.parentElement!==stack)lead.after(sys)}
function renderLead(reset=false){clearTimeout(leadTimer);const q=activeLeadQueue();if(reset)leadIndex=0;const bar=ensureBar('topActionBar','LEAD ALERTS');if(!q.length){leadIndex=0;paint(bar,'LEAD ALERTS','green','NO ACTIVE LEAD ALERTS','0 OPEN');syncDiag(q);schedulePopup();return}
  leadIndex=((leadIndex%q.length)+q.length)%q.length;const a=q[leadIndex],d=a._d;lastLeadKey=a._k;const owner=d.assignee&&!String(a.text||'').includes('Owner ')?` · Owner ${d.assignee}`:'';paint(bar,'LEAD ALERTS',a._sev,`${a.text||''}${owner}`,`← OPEN ${leadIndex+1} OF ${q.length}`,()=>typeof window.actionTarget==='function'&&window.actionTarget(a));syncDiag(q);schedulePopup();leadTimer=setTimeout(()=>{const next=activeLeadQueue();if(!next.length){renderLead(true);return}const p=next.findIndex(x=>x._k===lastLeadKey);leadIndex=((p<0?leadIndex:p)+1)%next.length;renderLead(false)},Math.max(3,Math.min(60,Number(d.seconds)||8))*1000)}
function renderSystem(reset=false){clearTimeout(systemTimer);const q=systemQueue();if(reset)systemIndex=0;const bar=ensureBar('operationsBar','SYSTEM STATUS');if(!q.length){systemIndex=0;paint(bar,'SYSTEM STATUS','green','ALL ACTIVE SYSTEMS NORMAL','0 OPEN');return}systemIndex=((systemIndex%q.length)+q.length)%q.length;const a=q[systemIndex];lastSystemKey=`${a.toolId||''}|${a.text||''}`;paint(bar,'SYSTEM STATUS',a._sev,a.text||'SYSTEM STATUS AVAILABLE',`← OPEN ${systemIndex+1} OF ${q.length}`,()=>a.toolId&&typeof window.toolStatus==='function'&&window.toolStatus(a.toolId));systemTimer=setTimeout(()=>{const next=systemQueue();if(!next.length){renderSystem(true);return}const p=next.findIndex(x=>`${x.toolId||''}|${x.text||''}`===lastSystemKey);systemIndex=((p<0?systemIndex:p)+1)%next.length;renderSystem(false)},8000)}
function refresh(reset=true){mountLive();homeBars();renderLead(reset);renderSystem(reset);setVersion()}
/* Legacy ticker guards look specifically for this name. Point them to the v0.80.19 engine. */
window.B7AlertEngine817={refresh,refreshLead:renderLead,refreshSystem:renderSystem,leadQueue:activeLeadQueue,systemQueue};window.B7AlertEngine819=window.B7AlertEngine817;window.renderTopActionBar=function(){renderLead(false)};window.updateOperationsBar=function(){renderSystem(false)};
function toast(text){let t=$('#v819Toast');if(!t){t=document.createElement('div');t.id='v819Toast';t.className='v819-toast';document.body.appendChild(t)}t.textContent=text;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2000)}
function cardKey(card){return String(card?.dataset?.auto51||'')}
function manualCard(card){return cardKey(card).startsWith('manual:')}
function serialize(card){return JSON.stringify({assignee:card.querySelector('.ac-owner51')?.value.trim()||'',show:(card.querySelector('.ac-show51')?.value||'on')==='on',seconds:Number(card.querySelector('.ac-sec51')?.value)||8,order:Number(card.querySelector('.ac-order51')?.value)||999,pin:!!card.querySelector('.ac-pin51')?.checked,ack:!!card.querySelector('.ac-ack51')?.checked,mode:card.querySelector('.ac-until-mode51')?.value||'while-open',custom:card.querySelector('.ac-until51')?.value||''})}
function persistCard(card){const k=cardKey(card);if(!k)return false;const v=JSON.parse(serialize(card)),d=ctl(k,{});Object.assign(d,{assignee:v.assignee,show:v.show,seconds:v.seconds,order:v.order,pin:v.pin,ack:v.ack,displayUntil:v.mode==='while-open'?'while-open':v.mode==='today'?todayISO():(v.custom||'while-open')});state.actionDisplay[k]=d;card.classList.toggle('v819-alert-off',!d.show);card.classList.remove('v819-dirty');actionSnapshots.set(card,serialize(card));return true}
function saveStore(){try{if(typeof window.save==='function')window.save()}catch(e){}refresh(true)}
function deleteManual(card){if(!manualCard(card))return;const id=cardKey(card).slice(7);if(!confirm('Permanently delete this manually-created alert/task? This cannot be undone.'))return;state.manualReminders=state.manualReminders.filter(r=>String(r.id)!==id);delete state.actionDisplay[cardKey(card)];delete state.actionDisplay[id];delete state.actionFirstSeen?.[cardKey(card)];saveStore();rerenderActions();toast('Manual alert deleted')}
function resolveManual(card){if(!manualCard(card))return;const id=cardKey(card).slice(7),r=state.manualReminders.find(x=>String(x.id)===id);if(!r)return;const note=prompt('Optional resolution note:','');if(note===null)return;state.actionHistory.unshift({...JSON.parse(JSON.stringify(r)),historyId:'hist'+Date.now(),resolvedAt:new Date().toISOString(),resolutionNote:note});r.complete=true;r.resolvedAt=new Date().toISOString();saveStore();rerenderActions();toast('Manual alert resolved and moved to history')}
function actionRow(card){const controls=card.querySelector('.auto-controls51');if(!controls)return;let row=controls.querySelector('.v819-card-actions');if(!row){row=document.createElement('div');row.className='v819-card-actions';controls.appendChild(row)}row.replaceChildren();const note=document.createElement('span');note.className='v819-card-note';note.textContent=manualCard(card)?'MANUAL · USER CONTROLLED':'AUTO · CLEARS ONLY FROM TOOL / WORKFLOW';row.appendChild(note);const dirty=document.createElement('span');dirty.className='v819-dirty-badge';dirty.textContent='UNSAVED CHANGES';row.appendChild(dirty);const save=document.createElement('button');save.type='button';save.className='btn small primary v819-save';save.textContent='SAVE CHANGES';save.onclick=e=>{e.preventDefault();if(!card.classList.contains('v819-dirty')){toast('No changes to save');return}persistCard(card);saveStore();toast('Saved 1 changed alert')};row.appendChild(save);if(manualCard(card)){const res=document.createElement('button');res.type='button';res.className='btn small v819-resolve';res.textContent='RESOLVE';res.onclick=e=>{e.preventDefault();if(card.classList.contains('v819-dirty'))persistCard(card);resolveManual(card)};row.appendChild(res);const del=document.createElement('button');del.type='button';del.className='btn small v819-delete';del.textContent='DELETE';del.onclick=e=>{e.preventDefault();deleteManual(card)};row.appendChild(del)}}
function syncCard(card){const k=cardKey(card);if(!k)return;const a=rawAlerts().find(x=>actionKey(x)===k)||{},d=ctl(k,a);const show=card.querySelector('.ac-show51');if(show)show.value=d.show===false?'off':'on';const owner=card.querySelector('.ac-owner51');if(owner)owner.value=d.assignee||'';const sec=card.querySelector('.ac-sec51');if(sec&&[...sec.options].some(o=>Number(o.value)===Number(d.seconds)))sec.value=String(d.seconds);const order=card.querySelector('.ac-order51');if(order)order.value=Number(d.order)||999;const pin=card.querySelector('.ac-pin51');if(pin)pin.checked=!!d.pin;const ack=card.querySelector('.ac-ack51');if(ack)ack.checked=!!d.ack;const mode=card.querySelector('.ac-until-mode51'),custom=card.querySelector('.ac-until51');if(mode){if(d.displayUntil==='while-open')mode.value='while-open';else if(d.displayUntil===todayISO())mode.value='today';else mode.value='custom'}if(custom)custom.value=/^\d{4}-/.test(d.displayUntil||'')?d.displayUntil:'';card.classList.toggle('v819-alert-off',d.show===false);card.classList.remove('v819-dirty');actionSnapshots.set(card,serialize(card));actionRow(card)}
function syncDiag(q=activeLeadQueue()){let host=$('#v819QueueDiag');if(!host){const summary=$('.action-summary-grid');if(summary){host=document.createElement('div');host.id='v819QueueDiag';host.className='v819-queue-diag';summary.insertAdjacentElement('afterend',host)}}if(!host)return;const c={red:0,orange:0,yellow:0,blue:0};q.forEach(x=>c[x._sev]=(c[x._sev]||0)+1);host.innerHTML=`<strong>ACTIVE LEAD ALERTS: ${q.length}</strong> · Critical ${c.red||0} · Attention ${c.orange||0} · Reminder ${c.yellow||0} · Information ${c.blue||0}`}
function enhanceActions(){if(document.body.dataset.center!=='action')return;migrateManual();$$('.auto-action51[data-auto51]').forEach(card=>syncCard(card));const app=$('#app');if(app&&!app.dataset.v819DirtyBound){app.dataset.v819DirtyBound='1';const mark=e=>{const card=e.target.closest('.auto-action51[data-auto51]');if(!card||!e.target.closest('.auto-controls51'))return;const snap=actionSnapshots.get(card);if(snap!==undefined)card.classList.toggle('v819-dirty',serialize(card)!==snap)};app.addEventListener('input',mark);app.addEventListener('change',mark)}syncDiag();const saveAll=$('#v815SaveAll');if(saveAll){saveAll.textContent='SAVE ALL CHANGES';saveAll.onclick=e=>{e.preventDefault();const dirty=$$('.auto-action51.v819-dirty[data-auto51]');if(!dirty.length){toast('No changes to save');return}dirty.forEach(persistCard);saveStore();toast(`Saved ${dirty.length} changed alert${dirty.length===1?'':'s'}`)}}}
function rerenderActions(){if(window.B7Renderers58?.actionCenter){window.B7Renderers58.actionCenter();setTimeout(enhanceActions,0)}else if(typeof window.setView==='function')window.setView('actions')}
/* Critical popup is driven by the SAME active queue as Lead Alerts. */
function closePopup(){$('#v819Critical')?.remove()}
function criticalEligible(){if(viewerOnly||document.body.classList.contains('v802-live-status'))return null;const now=Date.now();return activeLeadQueue().find(a=>a._sev==='red'&&!a._d.ack&&(!a._d.snoozeUntil||Number(a._d.snoozeUntil)<=now))||null}
function showPopup(a){if(!a||$('#v819Critical'))return;document.body.insertAdjacentHTML('beforeend',`<div id="v819Critical" class="v819-critical-backdrop"><section class="v819-critical-modal" role="alertdialog" aria-modal="true"><div class="v819-critical-head"><span class="v819-status-lamp"></span><div><strong>LEAD ALERTS</strong><br><span>CRITICAL — REQUIRES ATTENTION</span></div></div><div class="v819-critical-body"></div><div class="v819-critical-actions"><button class="btn primary" data-v819-ack>ACKNOWLEDGE & WORKING</button><button class="btn" data-v819-open>OPEN ACTION CENTER</button><button class="btn" data-v819-later>REMIND ME LATER</button></div></section></div>`);$('#v819Critical .v819-critical-body').textContent=a.text||'Critical alert';$('[data-v819-ack]').onclick=()=>{a._d.ack=true;a._d.acknowledgedAt=new Date().toISOString();state.actionDisplay[a._k]=a._d;saveStore();closePopup()};$('[data-v819-open]').onclick=()=>{closePopup();window.setView?.('actions')};$('[data-v819-later]').onclick=()=>{a._d.snoozeUntil=Date.now()+30*60*1000;state.actionDisplay[a._k]=a._d;try{window.save?.()}catch(e){}closePopup();schedulePopup()}}
function schedulePopup(){clearTimeout(popupTimer);closePopup();const a=criticalEligible();if(!a)return;popupTimer=setTimeout(()=>{const current=criticalEligible();if(current&&current._k===a._k)showPopup(current)},30000)}
const priorSetView=window.setView;if(typeof priorSetView==='function')window.setView=function(v){const out=priorSetView.apply(this,arguments);setTimeout(()=>{mountLive();homeBars();refresh(true);if(v==='actions')enhanceActions();setVersion()},0);setTimeout(()=>{if(v==='actions')enhanceActions();setVersion()},80);return out};
function boot(){migrateManual();setVersion();mountLive();homeBars();refresh(true);enhanceActions();setTimeout(()=>{mountLive();homeBars();refresh(false);enhanceActions();setVersion()},120)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.addEventListener('storage',()=>{migrateManual();refresh(true);if(document.body.dataset.center==='action')enhanceActions()});
})();
