/* B7 FI Command Center v0.80.54 — Centralized Page Navigation Framework
   One authoritative secondary toolbar. Left = destinations, right = actions.
   Removes the v0.80.53 delayed toolbar recovery layer that caused jumpy controls.
*/
(function(){'use strict';
const VERSION='0.80.54';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
window.B7_APP_VERSION=VERSION;window.VERSION=VERSION;
function q(){try{return String(window.getB7ActiveQuarter?.()||window.quarterLabel?.()||'CY26Q3').toUpperCase()}catch(e){return'CY26Q3'}}
function allTools(){try{return Array.isArray(window.tools)?window.tools:(Array.isArray(tools)?tools:[])}catch(e){return[]}}
function shot(){try{if(typeof window.enterScreenshotMode==='function')return window.enterScreenshotMode()}catch(e){}try{if(typeof window.enterScreenshot==='function')return window.enterScreenshot()}catch(e){}window.print()}
function report(){try{if(typeof window.openReport530==='function')return window.openReport530()}catch(e){}window.print()}
function B(label,fn,primary=false,danger=false){const b=document.createElement('button');b.type='button';b.className='btn'+(primary?' primary':'')+(danger?' danger':'');b.textContent=label;b.onclick=fn;return b}
function toolbar(left=[],right=[]){const bar=$('#floatingActions');if(!bar)return;bar.className='floating-actions page-toolbar v854-toolbar';bar.innerHTML='';const l=document.createElement('div'),r=document.createElement('div');l.className='v854-nav-left';r.className='v854-actions-right';left.filter(Boolean).forEach(x=>l.appendChild(x));right.filter(Boolean).forEach(x=>r.appendChild(x));bar.append(l,r)}
function stamp(){document.title=`B7 FI Command Center v${VERSION}`;const v=$('#appVersionLabel');if(v)v.textContent=`B7 FI COMMAND CENTER V${VERSION}`}
function callAdmin(section){try{if(typeof window.admin==='function')return window.admin(section);if(typeof admin==='function')return admin(section)}catch(e){}}
function toolsNav(active){return [B(`${q()} TOOLS`,()=>window.setView('toolcenter'),active==='tools'),B('TOOL COUNTDOWN',()=>window.setView('countdown'),active==='countdown'),B('TOOL ARCHIVE',()=>window.setView('archive'),active==='archive')]}
function toolTheme(title){document.body.dataset.center='toolfinal';document.body.dataset.theme='toolcenter';document.documentElement.style.setProperty('--page-accent','#8b5cf6');document.documentElement.style.setProperty('--page-accent-rgb','139,92,246');const h=$('#headerPageTitle');if(h)h.textContent=title;$$('.main-nav .nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view==='toolcenter'))}
function activeTools(){return allTools().filter(t=>String(t.quarterStatus||t.status||'').toLowerCase()!=='archive')}
function archivedTools(){return allTools().filter(t=>String(t.quarterStatus||t.status||'').toLowerCase()==='archive')}
function fmt(v){if(!v)return'—';try{const d=new Date(String(v).slice(0,10)+'T00:00:00');return isNaN(d)?String(v):d.toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric'})}catch(e){return String(v)}}
function saveMaster(){try{return window.save?.()}catch(e){try{return save()}catch(_){}}}
function openTool(id){if(typeof window.toolStatus==='function')window.toolStatus(String(id))}

/* Tool Archive: one bulk workflow, one master record. */
function renderArchive(){toolTheme('TOOL ARCHIVE');const app=$('#app');if(!app)return;const list=archivedTools();app.innerHTML=`<div class="v854-simple"><div class="table-wrap"><table class="report-table"><thead><tr><th>UTID</th><th>CODE NAME</th><th>MODEL</th><th>CUSTOMER</th><th>SALES ORDER</th><th>SHIP DATE</th><th>QUARTER</th><th>ARCHIVED</th></tr></thead><tbody>${list.map(t=>`<tr data-v854-tool="${esc(t.id||t.utid)}"><td><b>${esc(t.id||t.utid)}</b></td><td>${esc(t.codename||t.codeName||'—')}</td><td>${esc(t.model||'—')}</td><td>${esc(t.customer||'—')}</td><td>${esc(t.so||t.salesOrder||'—')}</td><td>${esc(fmt(t.ship||t.shipDate))}</td><td>${esc(t.quarter||'—')}</td><td>${esc(fmt(t.archiveDate))}</td></tr>`).join('')||'<tr><td colspan="8" class="gray">No archived tools.</td></tr>'}</tbody></table></div></div>`;toolbar(toolsNav('archive'),[B('ARCHIVE TOOL',renderArchiveMode,true),B('SCREENSHOT',shot),B('REPORT',report)]);$$('[data-v854-tool]',app).forEach(r=>r.onclick=()=>openTool(r.dataset.v854Tool))}
function renderArchiveMode(){toolTheme('TOOL ARCHIVE');const app=$('#app');if(!app)return;const list=activeTools();app.innerHTML=`<div class="v854-simple"><div class="table-wrap"><table class="report-table"><thead><tr><th>UTID</th><th>CODE NAME</th><th>MODEL</th><th>CUSTOMER</th><th>CURRENT STATUS</th><th>NEW STATUS</th></tr></thead><tbody>${list.map(t=>`<tr><td><b>${esc(t.id||t.utid)}</b></td><td>${esc(t.codename||t.codeName||'—')}</td><td>${esc(t.model||'—')}</td><td>${esc(t.customer||'—')}</td><td>${esc(t.quarterStatus||t.status||'Waiting to be Handed to FI')}</td><td><select class="v854-archive" data-id="${esc(t.id||t.utid)}"><option value="">No Change</option><option value="Archive">Archive</option></select></td></tr>`).join('')||'<tr><td colspan="6" class="gray">No active tools available to archive.</td></tr>'}</tbody></table></div><div id="v854ArchiveNotice" class="v854-notice"></div></div>`;toolbar(toolsNav('archive'),[B('CANCEL',renderArchive),B('SAVE',saveArchive,true)])}
function saveArchive(){const ids=$$('.v854-archive').filter(x=>x.value==='Archive').map(x=>String(x.dataset.id));if(!ids.length){const n=$('#v854ArchiveNotice');if(n)n.textContent='No changes to save.';return}const today=new Date().toISOString().slice(0,10);allTools().forEach(t=>{if(ids.includes(String(t.id||t.utid))){t.quarterStatus='Archive';t.status='Archive';t.archiveDate=t.archiveDate||today}});saveMaster();try{document.dispatchEvent(new CustomEvent('b7fi:tool-records-updated',{detail:{reason:'archive',ids}}))}catch(e){}renderArchive();const n=document.createElement('div');n.className='v854-ack';n.textContent=ids.length===1?`✓ Tool ${ids[0]} moved to Archive`:`✓ ${ids.length} tools moved to Archive`;$('#app')?.prepend(n);setTimeout(()=>n.remove(),3500)}

/* Generic edit mode: move legacy save/cancel behavior into the page toolbar. */
function bodyButton(re){return $$('#app button').find(b=>re.test(String(b.textContent||'').trim()))}
function editToolbar(left,saveRe,cancelFn,saveLabel='SAVE'){const saveBtn=bodyButton(saveRe);if(saveBtn)saveBtn.style.display='none';toolbar(left,[B('CANCEL',cancelFn),B(saveLabel,()=>{if(saveBtn)saveBtn.click()},true)])}

/* Priority Center */
function renderPriority(kind='weekday'){if(kind==='weekend'){try{if(typeof weekend==='function')weekend();else priorSetView('weekend')}catch(e){priorSetView('weekend')}}else{try{if(typeof daily==='function')daily();else priorSetView('priorities')}catch(e){priorSetView('priorities')}}const left=[B('WEEKDAY PRIORITIES',()=>renderPriority('weekday'),kind==='weekday'),B('WEEKEND PRIORITIES',()=>renderPriority('weekend'),kind==='weekend')];toolbar(left,[B(kind==='weekday'?'EDIT WEEKDAY PRIORITIES':'EDIT WEEKEND PRIORITIES',()=>editPriority(kind),true),B('SCREENSHOT',shot),B('REPORT',report)])}
function editPriority(kind){callAdmin(kind==='weekday'?'daily':'weekend');requestAnimationFrame(()=>editToolbar([B('WEEKDAY PRIORITIES',()=>renderPriority('weekday'),kind==='weekday'),B('WEEKEND PRIORITIES',()=>renderPriority('weekend'),kind==='weekend')],/^Save .*Priorit/i,()=>renderPriority(kind)))}

/* Shipping Center: generated view, actions only. */
function renderShipping(){priorSetView('shipping');toolbar([],[B('EDIT SHIP SCHEDULE',renderShipChooser,true),B('SCREENSHOT',shot),B('REPORT',report)])}
function renderShipChooser(){const app=$('#app');if(!app)return;const list=activeTools().slice().sort((a,b)=>String(a.ship||'9999').localeCompare(String(b.ship||'9999')));app.innerHTML=`<div class="v854-simple"><div class="panel"><h2>EDIT SHIP SCHEDULE</h2><p class="gray">Choose the tool whose master shipping schedule you want to edit.</p><div class="table-wrap"><table class="report-table"><thead><tr><th></th><th>UTID</th><th>CODE NAME</th><th>MODEL</th><th>CUSTOMER</th><th>SHIP DATE</th><th>SHIPPING STATUS</th></tr></thead><tbody>${list.map((t,i)=>`<tr><td><input type="radio" name="v854ShipTool" value="${esc(t.id||t.utid)}" ${i===0?'checked':''}></td><td><b>${esc(t.id||t.utid)}</b></td><td>${esc(t.codename||'—')}</td><td>${esc(t.model||'—')}</td><td>${esc(t.customer||'—')}</td><td>${esc(fmt(t.ship||t.shipDate))}</td><td>${esc(t.schedule?.status||t.quarterStatus||'—')}</td></tr>`).join('')||'<tr><td colspan="7" class="gray">No active tools.</td></tr>'}</tbody></table></div></div></div>`;toolbar([],[B('CANCEL',renderShipping),B('EDIT SELECTED TOOL',()=>{const id=$('input[name="v854ShipTool"]:checked')?.value;if(id)window.toolAdmin?.(id)},true)])}

/* Status Center */
function statusLeft(active){return [B('WEEKDAY MORNING STATUS',()=>renderStatus('weekday'),active==='weekday'),B('LEADS EXTRA STATUS',()=>renderStatus('extra'),active==='extra'),B('WEEKEND MORNING STATUS',()=>renderStatus('weekend'),active==='weekend')]}
function renderStatus(kind='weekday'){if(kind==='weekday')priorSetView('statuscenter');else if(kind==='extra')priorSetView('leads');else renderWeekend(false);toolbar(statusLeft(kind),[B(kind==='weekday'?'EDIT WEEKDAY MORNING STATUS':kind==='extra'?'EDIT LEADS EXTRA STATUS':'EDIT WEEKEND MORNING STATUS',()=>editStatus(kind),true),B('SCREENSHOT',shot),B('REPORT',report)])}
function editStatus(kind){if(kind==='weekday'){callAdmin('meeting');requestAnimationFrame(()=>editToolbar(statusLeft(kind),/^Save Morning/i,()=>renderStatus(kind)))}else if(kind==='extra'){renderStatus('extra');requestAnimationFrame(()=>{const x=bodyButton(/^Edit Leads Extra Status$/i);if(x)x.click();requestAnimationFrame(()=>editToolbar(statusLeft(kind),/^Save/i,()=>renderStatus(kind)))})}else renderWeekend(true)}
function renderWeekend(edit){document.body.dataset.center='status';document.body.dataset.theme='status';const h=$('#headerPageTitle');if(h)h.textContent=`STATUS CENTER — ${q()}`;let st;try{st=window.state||state}catch(e){st={}};st.weekendMorningStatus=st.weekendMorningStatus||{lead:'',date:'',notes:'',updatedAt:''};const w=st.weekendMorningStatus,app=$('#app');if(!app)return;const list=activeTools().filter(t=>t.weekendPriority).sort((a,b)=>(a.weekendPriority||999)-(b.weekendPriority||999));const rows=list.map(t=>`<tr><td>${esc(t.weekendPriority||'')}</td><td><b>${esc(t.id||t.utid)}</b></td><td>${esc(t.codename||'—')}</td><td>${esc(t.customer||'—')}</td><td>${esc(fmt(t.ship||t.shipDate))}</td><td>${esc(t.weekendAssignment||t.driver||'')}</td><td>${esc(t.weekendNotes||'')}</td></tr>`).join('')||'<tr><td colspan="7">No weekend priorities assigned.</td></tr>';if(edit){app.innerHTML=`<div class="v854-simple"><div class="form-grid"><label>Weekend Lead<input id="v854WLead" value="${esc(w.lead)}"></label><label>Date<input id="v854WDate" type="date" value="${esc(w.date)}"></label></div><label>Weekend Status Notes<textarea id="v854WNotes" rows="7">${esc(w.notes)}</textarea></label><div class="table-wrap"><table class="report-table"><thead><tr><th>Priority</th><th>UTID</th><th>Code Name</th><th>Customer</th><th>Ship Date</th><th>Assignment</th><th>Notes</th></tr></thead><tbody>${rows}</tbody></table></div></div>`;toolbar(statusLeft('weekend'),[B('CANCEL',()=>renderWeekend(false)),B('SAVE',()=>{w.lead=$('#v854WLead')?.value.trim()||'';w.date=$('#v854WDate')?.value||'';w.notes=$('#v854WNotes')?.value||'';w.updatedAt=new Date().toISOString();saveMaster();renderWeekend(false)},true)])}else{app.innerHTML=`<div class="v854-simple"><div class="panel"><b>${esc(w.date||'Weekend Morning Status')}</b> · Weekend Lead: ${esc(w.lead||'Not assigned')}${w.notes?`<p>${esc(w.notes).replace(/\n/g,'<br>')}</p>`:''}</div><div class="table-wrap"><table class="report-table"><thead><tr><th>Priority</th><th>UTID</th><th>Code Name</th><th>Customer</th><th>Ship Date</th><th>Assignment</th><th>Notes</th></tr></thead><tbody>${rows}</tbody></table></div></div>`;toolbar(statusLeft('weekend'),[B('EDIT WEEKEND MORNING STATUS',()=>renderWeekend(true),true),B('SCREENSHOT',shot),B('REPORT',report)])}}

/* Meeting Center: meeting types in toolbar; body is history. */
const meetingTypes=['MORNING STATUS','LEADS MEETING','ORB MEETING','FE OPTIONS MEETING','CELL MEETING'];let meetingType='MORNING STATUS';
function renderMeeting(type=meetingType){meetingType=type;priorSetView('meetingcenter');requestAnimationFrame(()=>{const start=$('.start-now51'),grid=$('.meeting-template-grid51');if(start)start.style.display='none';if(grid)grid.style.display='none';const history=$$('#app .meeting-record51');history.forEach(d=>{const s=(d.querySelector('summary')?.textContent||'').toUpperCase();d.style.display=s.includes(type.replace('MORNING STATUS','MORNING'))?'':'none'});toolbar(meetingTypes.map(x=>B(x,()=>renderMeeting(x),x===type)),[B(`START ${type}`,()=>startMeeting(type),true),B('SCREENSHOT',shot),B('REPORT',report)])})}
function startMeeting(type){const hidden=$$('.meeting-template51').find(b=>(b.textContent||'').toUpperCase().includes(type.replace('MORNING STATUS','MORNING')));if(hidden)hidden.click();else{const input=$('#adhocTitle51'),go=$('#adhocStart51');if(input&&go){input.value=type;go.click()}}requestAnimationFrame(()=>{const saveBtn=$('#saveMeet51');if(saveBtn)saveBtn.style.display='none';toolbar(meetingTypes.map(x=>B(x,()=>renderMeeting(x),x===type)),[B('CANCEL',()=>renderMeeting(type)),B('SAVE',()=>saveBtn?.click(),true)])})}

/* Action Center: generated page, actions only. */
function renderAction(){priorSetView('actions');toolbar([],[B('ADD ALERT',renderAddAlert,true),B('SCREENSHOT',shot),B('REPORT',report)])}
function renderAddAlert(){const app=$('#app');if(!app)return;app.innerHTML=`<div class="v854-simple"><div class="panel"><h2>ADD ALERT</h2><div class="form-grid"><label>Type<select id="v854AlertType"><option>Lead Alert</option><option>System Status Alert</option><option>Task</option><option>Reminder</option></select></label><label>Related Tool<select id="v854AlertTool"><option value="">General</option>${activeTools().map(t=>`<option value="${esc(t.id||t.utid)}">${esc(t.id||t.utid)} · ${esc(t.codename||'')}</option>`).join('')}</select></label><label class="wide">Message<input id="v854AlertMsg" placeholder="Alert / task / reminder text"></label><label>Owner<input id="v854AlertOwner"></label><label>Due Date<input id="v854AlertDue" type="date"></label></div></div></div>`;toolbar([],[B('CANCEL',renderAction),B('SAVE',saveAlert,true)])}
function saveAlert(){const msg=$('#v854AlertMsg')?.value.trim();if(!msg)return alert('Message is required.');let st;try{st=window.state||state}catch(e){st={}};st.workspaceTasks=Array.isArray(st.workspaceTasks)?st.workspaceTasks:[];const type=$('#v854AlertType')?.value||'Lead Alert';st.workspaceTasks.unshift({id:'manual-'+Date.now(),title:msg,toolId:$('#v854AlertTool')?.value||'',assignee:$('#v854AlertOwner')?.value.trim()||'',due:$('#v854AlertDue')?.value||'',status:'Open',priority:type==='System Status Alert'?'Critical':'Normal',source:`Manual ${type}`,createdAt:new Date().toISOString(),showTicker:true,alertType:type});saveMaster();renderAction()}

/* Reference Center */
function refLeft(active){return [B('FI KNOWLEDGE',()=>renderReference('knowledge'),active==='knowledge'),B('REFERENCE FILES',()=>renderReference('files'),active==='files')]}
function renderReference(kind='knowledge'){if(kind==='knowledge'){priorSetView('referencecenter');toolbar(refLeft('knowledge'),[B('ADD REFERENCE NOTE',()=>{const x=bodyButton(/ADD REFERENCE NOTE/i);if(x)x.click()},true),B('SCREENSHOT',shot),B('REPORT',report)])}else renderReferenceFiles()}
function renderReferenceFiles(){document.body.dataset.center='reference';document.body.dataset.theme='reference';const h=$('#headerPageTitle');if(h)h.textContent='REFERENCE CENTER';const app=$('#app');if(!app)return;app.innerHTML=`<div class="v854-file-page"><div class="v854-file-meta" id="v854FileMeta">No reference file loaded.</div><div class="v854-file-viewer" id="v854FileViewer"><div class="gray">Use LOAD FILE to open a local file or shared/network URL.</div></div><input id="v854LocalFile" type="file" hidden></div>`;toolbar(refLeft('files'),[B('LOAD FILE',openFileLoader,true),B('SCREENSHOT',shot),B('REPORT',report)])}
function openFileLoader(){const mode=prompt('Load reference file:\n1 = Local file\n2 = Shared/network URL','1');if(mode==='1'){$('#v854LocalFile')?.click()}else if(mode==='2'){const url=prompt('Paste the shared/network file URL:','');if(url)showFileUrl(url)}const inp=$('#v854LocalFile');if(inp&&!inp.dataset.wired){inp.dataset.wired='1';inp.onchange=()=>{const f=inp.files?.[0];if(!f)return;const url=URL.createObjectURL(f);$('#v854FileMeta').textContent=`Loaded: ${f.name} · Local file`;showFileUrl(url,f.name)}}}
function showFileUrl(url,name='Shared / network file'){const meta=$('#v854FileMeta'),viewer=$('#v854FileViewer');if(meta)meta.textContent=`Loaded: ${name}`;if(viewer)viewer.innerHTML=`<iframe title="Reference File Viewer" src="${esc(url)}"></iframe>`}

/* Search Center: body search only; toolbar actions only. */
function renderSearch(){priorSetView('searchcenter');toolbar([],[B('SCREENSHOT',shot),B('REPORT',report)])}

const priorSetView=window.setView;
window.setView=function(v){window.scrollTo(0,0);if(v==='archive')return renderArchive();if(v==='shipping')return renderShipping();if(v==='priorities')return renderPriority('weekday');if(v==='weekend')return renderPriority('weekend');if(v==='statuscenter')return renderStatus('weekday');if(v==='leads')return renderStatus('extra');if(v==='meetingcenter')return renderMeeting();if(v==='actions')return renderAction();if(v==='referencecenter')return renderReference('knowledge');if(v==='references')return renderReference('files');if(v==='searchcenter')return renderSearch();const out=priorSetView.apply(this,arguments);if(v==='toolcenter'||v==='systems')requestAnimationFrame(()=>toolbar(toolsNav('tools'),[B('ADD TOOL',()=>window.toolAdmin?.(),true),B('SCREENSHOT',shot),B('REPORT',report)]));if(v==='countdown')requestAnimationFrame(()=>toolbar(toolsNav('countdown'),[B('ADD TOOL',()=>window.toolAdmin?.(),true),B('SCREENSHOT',shot),B('REPORT',report)]));return out};try{setView=window.setView}catch(e){}

/* Canonical Tool Detail / Tool Edit actions. */
const priorToolStatus=window.toolStatus;if(typeof priorToolStatus==='function'){window.toolStatus=function(id){const out=priorToolStatus.apply(this,arguments);requestAnimationFrame(()=>{toolTheme(`TOOL ${id}`);toolbar(toolsNav('tools'),[B('EDIT TOOL',()=>window.toolAdmin?.(id),true),B('SCREENSHOT',shot),B('REPORT',report)])});return out};try{toolStatus=window.toolStatus}catch(e){}}
const priorToolAdmin=window.toolAdmin;if(typeof priorToolAdmin==='function'){window.toolAdmin=function(id){const out=priorToolAdmin.apply(this,arguments);requestAnimationFrame(()=>{const buttons=$$('#floatingActions button'),saveB=buttons.find(b=>/^SAVE TOOL$/i.test((b.textContent||'').trim())),delB=buttons.find(b=>/^DELETE TOOL$/i.test((b.textContent||'').trim()));const saveFn=saveB?.onclick?saveB.onclick.bind(saveB):null,delFn=delB?.onclick?delB.onclick.bind(delB):null;toolTheme(id?`TOOL ${id} — EDIT`:'ADD TOOL');toolbar(toolsNav('tools'),[B('CANCEL',()=>id?window.toolStatus(id):window.setView('toolcenter')),B('SAVE TOOL',()=>saveFn?.(),true),id?B('DELETE TOOL',()=>delFn?.(),false,true):null].filter(Boolean))});return out};try{toolAdmin=window.toolAdmin}catch(e){}}

function boot(){stamp();$$('.main-nav .nav-btn').forEach(b=>b.onclick=()=>window.setView(b.dataset.view));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
