/* B7 FI Command Center v0.80.36 — canonical tool record + route persistence + center-to-tool editing */
(function(){
'use strict';
const VERSION='0.80.36', $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
window.B7_APP_VERSION=VERSION;window.VERSION=VERSION;
function stamp(){document.title=`B7 FI Command Center v${VERSION}`;const x=$('#appVersionLabel');if(x)x.textContent=`B7 FI COMMAND CENTER V${VERSION}`}
function qFromDate(v){const m=String(v||'').match(/^(\d{4})-(\d{2})/);return m?`CY${m[1].slice(-2)}Q${Math.floor((+m[2]-1)/3)+1}`:''}
function remember(route){try{sessionStorage.setItem('b7.route',JSON.stringify(route));history.replaceState(route,'',location.pathname+'#'+encodeURIComponent(JSON.stringify(route)))}catch(e){}}
function parseRoute(){try{if(location.hash.length>2)return JSON.parse(decodeURIComponent(location.hash.slice(1)));return JSON.parse(sessionStorage.getItem('b7.route')||'null')}catch(e){return null}}
const _setView=window.setView; if(typeof _setView==='function') window.setView=function(v){remember({kind:'view',view:v});return _setView.apply(this,arguments)};
const _toolStatus=window.toolStatus; if(typeof _toolStatus==='function') window.toolStatus=function(id){remember({kind:'tool',id:String(id)});const r=_toolStatus.apply(this,arguments);document.body.dataset.theme='systems';return r};
const _toolAdmin=window.toolAdmin; if(typeof _toolAdmin==='function') window.toolAdmin=function(id,requestedTab){remember({kind:'editTool',id:id?String(id):'',tab:requestedTab||'basic'});const r=_toolAdmin.call(this,id);setTimeout(()=>enhanceToolEditor(id,requestedTab),0);return r};
function enhanceToolEditor(id,requestedTab){
  document.body.dataset.theme='systems';
  const t=(window.tools||[]).find(x=>String(x.id)===String(id||''));
  const tabs=$$('.admin-tab[data-tab]');
  if(requestedTab){const b=tabs.find(x=>x.dataset.tab===requestedTab);if(b)b.click()}
  if(!id)return;
  const info=tabs.find(x=>x.dataset.tab==='basic');if(info)info.textContent='Tool Information / Plan';
  function inject(){const body=$('#taBody');if(!body||!$('#ta-ship')||$('#v836Plan'))return;const ship=$('#ta-ship').value;const cur=t||(window.tools||[]).find(x=>String(x.id)===String(id));const oq=cur?.originalQuarter||cur?.quarter||qFromDate(cur?.originalShip||ship);const cq=cur?.quarter||qFromDate(ship);body.insertAdjacentHTML('beforeend',`<section id="v836Plan" class="panel v836-plan-editor"><h3>Quarter / Ship Plan</h3><p class="helper">This Tool record is the source of truth. Changes here feed Tool Countdown, Shipping Center, Operations and Live Status.</p><div class="form-grid"><div class="form-group"><label>Current Quarter</label><input id="v836Quarter" value="${esc(cq)}"></div><div class="form-group"><label>Plan Change Type</label><select id="v836Change"><option>No Change</option><option>Ship Date Change</option><option>Pull In</option><option>Push Out</option></select></div><div class="form-group"><label>Original Quarter</label><input value="${esc(oq)}" disabled></div><div class="form-group wide"><label>Plan Change Reason / Notes</label><textarea id="v836Reason"></textarea></div></div></section>`)}
  inject();tabs.forEach(b=>b.addEventListener('click',()=>setTimeout(inject,0)));
  const toolbar=$('#floatingActions'); if(toolbar)toolbar.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!/save tool/i.test(b.textContent))return;const vals={ship:$('#ta-ship')?.value||'',quarter:$('#v836Quarter')?.value||'',type:$('#v836Change')?.value||'No Change',reason:$('#v836Reason')?.value||''};setTimeout(()=>{const x=(window.tools||[]).find(z=>String(z.id)===String(id));if(!x)return;const oldShip=x.ship||'',oldQ=x.quarter||qFromDate(oldShip);if(vals.quarter)x.quarter=vals.quarter;if(vals.type!=='No Change'&&(oldShip!==vals.ship||oldQ!==vals.quarter)){x.originalShip=x.originalShip||oldShip;x.originalQuarter=x.originalQuarter||oldQ;x.changeHistory=x.changeHistory||[];x.changeHistory.unshift({field:'MFG Ship / Quarter',oldValue:`${oldShip} · ${oldQ}`,newValue:`${vals.ship} · ${vals.quarter}`,type:vals.type,reason:vals.reason,changedAt:new Date().toISOString()});}try{window.save?.()}catch(e){}},0)},true)
}
/* Countdown is a fast, read-only quarter list. Tool-specific changes go to the canonical Tool editor. */
window.countdown=function(){
  const list=(window.pageTools?window.pageTools('countdown'):(window.tools||[])).slice().sort((a,b)=>String(a.ship||'9').localeCompare(String(b.ship||'9')));
  try{window.setHeaderContext?.('TOOL CENTER',window.quarterLabel?.()||'CURRENT QUARTER')}catch(e){}
  window.app.innerHTML=`<div class="report-screen"><div class="panel"><div class="subsection-title"><div><h2>${esc(window.quarterLabel?.()||'CURRENT QUARTER')} TOOL COUNTDOWN</h2><p class="helper">Fast quarter view. Click any tool to open its master Tool page.</p></div></div><div class="table-wrap"><table class="report-table v836-countdown"><thead><tr><th>UTID</th><th>Tool / Model</th><th>Customer</th><th>Sales Order</th><th>MFG Ship Date</th><th>Quarter</th><th>Plan Change</th><th>Status</th></tr></thead><tbody>${list.map(t=>{const h=(t.changeHistory||[])[0];return `<tr data-v836-tool="${esc(t.id)}"><td><b>${esc(t.id)}</b></td><td>${esc(t.codename)} · ${esc(t.model)}</td><td>${esc(t.customer)}</td><td>${esc(t.so)}</td><td>${esc(t.ship||'—')}</td><td>${esc(t.quarter||qFromDate(t.ship)||'—')}</td><td>${h?`<span class="badge info">${esc(h.type||'CHANGED')}</span>`:'—'}</td><td>${esc(t.quarterStatus)}</td></tr>`}).join('')}</tbody></table></div></div></div>`;
  $$('[data-v836-tool]').forEach(r=>r.onclick=()=>window.toolStatus(r.dataset.v836Tool));
  try{window.actions?.([{label:'CY26Q3 Tools',fn:()=>window.setView('systems')},{label:'Tool Archive',fn:()=>window.setView('archive')},{label:'Add Tool',primary:true,fn:()=>window.toolAdmin()}],false)}catch(e){}
};
/* Shipping Center is generated from Tool records; Edit Schedule selects a tool then deep-links to its Shipping tab. */
const _shipping=window.shipping; window.shipping=function(){const r=_shipping.apply(this,arguments);setTimeout(()=>{try{window.actions?.([{label:'CY26Q3 Shipping',primary:true,fn:()=>window.setView('shipping')},{label:'Edit Tool Schedule',fn:()=>openSchedulePicker()},{label:'Screenshot',fn:()=>window.enterScreenshotMode?.()},{label:'Report',fn:()=>window.print?.()}],false)}catch(e){}},0);return r};
function openSchedulePicker(){const old=$('#v836Picker');if(old)old.remove();const list=(window.tools||[]).filter(t=>t.quarterStatus!=='Archive');document.body.insertAdjacentHTML('beforeend',`<div id="v836Picker" class="v836-modal"><div class="panel"><h2>Edit Tool Shipping Schedule</h2><p class="helper">Choose a tool. Its master Tool editor will open directly to Shipping.</p><select id="v836Pick">${list.map(t=>`<option value="${esc(t.id)}">${esc(t.id)} — ${esc(t.codename)} ${esc(t.model)} — ${esc(t.customer)}</option>`).join('')}</select><div class="actions"><button id="v836Cancel" class="btn">Cancel</button><button id="v836Open" class="btn primary">Open Tool Schedule</button></div></div></div>`);$('#v836Cancel').onclick=()=>$('#v836Picker').remove();$('#v836Open').onclick=()=>{const id=$('#v836Pick').value;$('#v836Picker').remove();window.toolAdmin(id,'shipping')}}
/* Morning quick-edit: add the three occasionally-changing master fields to the existing Morning admin grid. */
const _admin=window.admin;if(typeof _admin==='function')window.admin=function(section){const r=_admin.apply(this,arguments);if(section==='meeting')setTimeout(enhanceMorning,0);return r};
function enhanceMorning(){const table=$('.morning-v3-table');if(!table||table.dataset.v836)return;table.dataset.v836='1';const hr=table.tHead?.rows?.[0];if(hr){['Ship Date','Sales Order','Customer'].forEach(x=>{const th=document.createElement('th');th.textContent=x;hr.insertBefore(th,hr.lastElementChild)})}$$('tbody tr[data-m3]',table).forEach(row=>{const t=(window.tools||[]).find(x=>String(x.id)===row.dataset.m3);const nc=row.lastElementChild;[['date','m3-ship',t?.ship||''],['text','m3-so',t?.so||''],['text','m3-customer',t?.customer||'']].forEach(([type,cls,val])=>{const td=document.createElement('td');td.innerHTML=`<input type="${type}" class="${cls}" value="${esc(val)}">`;row.insertBefore(td,nc)})});const saveBtn=$('#m3Save');if(saveBtn)saveBtn.addEventListener('click',()=>{const vals=$$('tbody tr[data-m3]',table).map(r=>({id:r.dataset.m3,ship:r.querySelector('.m3-ship')?.value||'',so:r.querySelector('.m3-so')?.value||'',customer:r.querySelector('.m3-customer')?.value||''}));setTimeout(()=>{vals.forEach(v=>{const t=(window.tools||[]).find(x=>String(x.id)===v.id);if(t){t.ship=v.ship;t.so=v.so;t.customer=v.customer}});try{window.save?.()}catch(e){}},0)},true)}
function restore(){stamp();const r=parseRoute();if(!r)return;if(r.kind==='tool'&&r.id)return window.toolStatus(r.id);if(r.kind==='editTool')return window.toolAdmin(r.id||undefined,r.tab||'basic');if(r.kind==='view'&&r.view)return _setView.call(window,r.view)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(restore,80),{once:true});else setTimeout(restore,80);
stamp();
})();
